import type { SeedLesson } from "./types";

// 10 intermediate & advanced lessons: KNOW_A_LITTLE → VIRTUOSO_REPERTOIRE.

export const advancedLessons: SeedLesson[] = [
  {
    slug: "circle-of-fifths",
    title: "The Circle of Fifths",
    description: "The map of all keys and how they relate.",
    category: "HARMONY",
    difficulty: 4,
    tierRequirement: "KNOW_A_LITTLE",
    order: 16,
    xpReward: 100,
    prerequisiteSlug: "cadences-and-accompaniment",
    content: [
      {
        heading: "The Wheel of Keys",
        body: "Arrange the twelve keys in a circle where each step clockwise adds a sharp (C → G → D → A …) and each step counter-clockwise adds a flat (C → F → B♭ …). Neighboring keys share six of seven notes — that's why moving to them feels smooth.",
        example: "Clockwise: C G D A E B F♯ · Counter-clockwise: C F B♭ E♭ A♭ D♭",
      },
      {
        heading: "A Composer's Compass",
        body: "The circle predicts modulation smoothness, explains why V is so closely bound to I (one step away), and organizes relative minors on an inner ring. Keep it in your head and key relationships stop being memorization.",
      },
    ],
    quiz: [
      {
        subject: "CIRCLE_OF_FIFTHS",
        difficulty: 4,
        prompt: "Moving clockwise one step on the circle of fifths from C lands on:",
        choices: ["F", "G", "D", "A"],
        answerIndex: 1,
        explanation: "Each clockwise step is up a fifth: C → G (one sharp).",
      },
      {
        subject: "CIRCLE_OF_FIFTHS",
        difficulty: 4,
        prompt: "How many notes do the keys of C major and G major share?",
        choices: ["4", "5", "6", "7"],
        answerIndex: 2,
        explanation: "Adjacent keys differ by exactly one note (F vs F♯) — six shared.",
      },
      {
        subject: "CIRCLE_OF_FIFTHS",
        difficulty: 4,
        prompt: "Which key has three flats?",
        choices: ["B♭ major", "E♭ major", "A♭ major", "F major"],
        answerIndex: 1,
        explanation: "F (1), B♭ (2), E♭ (3): E♭ major carries B♭, E♭, A♭.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Draw the Circle",
        prompt: "From memory, draw the full circle of fifths with sharps/flats counts and relative minors.",
      },
      {
        type: "COMPOSITION",
        title: "Neighboring Lands",
        prompt: "Write eight measures that begin in C major and end convincingly in G major, using the shared notes as a bridge.",
      },
    ],
    skillRewards: { HARMONY: 30, FORM: 10 },
  },
  {
    slug: "chord-functions-inversions",
    title: "Chord Functions and Inversions",
    description: "Tonic, predominant, dominant — and smooth bass lines through inversion.",
    category: "HARMONY",
    difficulty: 4,
    tierRequirement: "KNOW_A_LITTLE",
    order: 17,
    xpReward: 100,
    prerequisiteSlug: "circle-of-fifths",
    content: [
      {
        heading: "Three Jobs",
        body: "Every diatonic chord performs one of three functions: Tonic (I, vi — rest), Predominant (ii, IV — motion toward tension), Dominant (V, vii° — tension demanding rest). Progressions flow T → PD → D → T.",
      },
      {
        heading: "Inversions",
        body: "A chord keeps its identity whichever note is in the bass. Root position is solid; first inversion (third in bass) is lighter and mobile; second inversion is unstable and used in specific formulas like the cadential 6/4. Inversions let the bass sing its own line.",
        example: "C/E (first inversion) walks the bass smoothly: F → C/E → Dm → C.",
      },
    ],
    quiz: [
      {
        subject: "FUNCTIONS",
        difficulty: 4,
        prompt: "Which chords share the predominant function in major?",
        choices: ["I and vi", "ii and IV", "V and vii°", "iii and V"],
        answerIndex: 1,
        explanation: "ii and IV both set up the dominant.",
      },
      {
        subject: "INVERSIONS",
        difficulty: 4,
        prompt: "A first-inversion triad has which chord member in the bass?",
        choices: ["Root", "Third", "Fifth", "Seventh"],
        answerIndex: 1,
        explanation: "First inversion places the third in the bass.",
      },
      {
        subject: "INVERSIONS",
        difficulty: 5,
        prompt: "The cadential 6/4 chord typically resolves to:",
        choices: ["IV", "V", "vi", "ii"],
        answerIndex: 1,
        explanation: "The 6/4 over the dominant bass resolves its intervals down into V.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Function Labeling",
        prompt: "Label each chord T/PD/D: C – Am – Dm – G – C – F – G – C.",
      },
      {
        type: "COMPOSITION",
        title: "The Walking Bass",
        prompt: "Write a progression of eight chords where the bass moves only by step, using inversions as needed. Melody optional.",
      },
    ],
    skillRewards: { HARMONY: 30, COUNTERPOINT: 10 },
  },
  {
    slug: "modulation-secondary-dominants",
    title: "Modulation and Secondary Dominants",
    description: "Changing keys gracefully, and borrowing dominants along the way.",
    category: "HARMONY",
    difficulty: 5,
    tierRequirement: "KNOW_A_LITTLE",
    order: 18,
    xpReward: 110,
    prerequisiteSlug: "chord-functions-inversions",
    content: [
      {
        heading: "The Pivot",
        body: "The smoothest modulation reinterprets a chord both keys share: approach it as a chord of the old key, leave it as a chord of the new one, then confirm the arrival with the new key's V–I.",
        example: "C major → G major: Am is vi in C and ii in G. C – Am(pivot) – D7 – G.",
      },
      {
        heading: "Secondary Dominants",
        body: "Any major or minor chord can be preceded by its own dominant. V/V (in C: D7 before G) briefly tonicizes the destination, adding chromatic color without truly leaving the key.",
      },
    ],
    quiz: [
      {
        subject: "MODULATION",
        difficulty: 5,
        prompt: "A pivot chord is one that:",
        choices: [
          "Exists only in the new key",
          "Belongs to both the old and new keys",
          "Is always the tonic",
          "Contains no third",
        ],
        answerIndex: 1,
        explanation: "Shared membership lets the pivot face both directions.",
      },
      {
        subject: "SECONDARY_DOMINANTS",
        difficulty: 5,
        prompt: "In C major, the chord V/V is:",
        choices: ["G7", "D7", "A7", "E7"],
        answerIndex: 1,
        explanation: "The dominant of G (which is V) is D — so V/V = D7.",
      },
      {
        subject: "MODULATION",
        difficulty: 5,
        prompt: "What most convincingly confirms a new key after a pivot?",
        choices: [
          "A long rest",
          "A V–I cadence in the new key",
          "Repeating the pivot",
          "A tempo change",
        ],
        answerIndex: 1,
        explanation: "The authentic cadence plants the new tonic's flag.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Pivot Hunting",
        prompt: "List all chords shared by C major and F major, then write one pivot progression between them.",
      },
      {
        type: "COMPOSITION",
        title: "The Traveling Theme",
        prompt: "Write a theme in C major, then restate it in G major, connected by a pivot-chord modulation. About 16 measures.",
      },
    ],
    skillRewards: { HARMONY: 30, FORM: 15 },
  },
  {
    slug: "binary-ternary-form",
    title: "Binary, Ternary, and Variations",
    description: "The architecture of small forms: AB, ABA, and theme & variations.",
    category: "FORM",
    difficulty: 5,
    tierRequirement: "BASIC_COMPOSER",
    order: 19,
    xpReward: 110,
    prerequisiteSlug: "modulation-secondary-dominants",
    content: [
      {
        heading: "Two Rooms, Three Rooms",
        body: "Binary form (AB) presents an idea, then a contrasting or developing second half — often modulating to V in the A section and returning in B. Ternary form (ABA) adds the satisfaction of homecoming: statement, contrast, return.",
      },
      {
        heading: "Theme and Variations",
        body: "State a theme, then re-imagine it repeatedly: change its rhythm, mode, texture, or harmony while keeping something recognizable. Each variation should have one clear idea — variation is disciplined transformation, not decoration.",
        example: "Var 1: melody ornamented · Var 2: minor mode · Var 3: new accompaniment · Var 4: change of meter",
      },
    ],
    quiz: [
      {
        subject: "FORM",
        difficulty: 5,
        prompt: "Ternary form is best described as:",
        choices: ["AB", "ABA", "AAA", "ABC"],
        answerIndex: 1,
        explanation: "Statement, contrast, return: ABA.",
      },
      {
        subject: "FORM",
        difficulty: 5,
        prompt: "In rounded binary form, what 'rounds' the form?",
        choices: [
          "A drum roll",
          "The opening material returning at the end of the second section",
          "A fermata",
          "A key change",
        ],
        answerIndex: 1,
        explanation: "The A idea returns inside B, rounding the shape.",
      },
      {
        subject: "FORM",
        difficulty: 5,
        prompt: "The strongest variations usually:",
        choices: [
          "Change everything at once",
          "Keep one element recognizable while transforming another",
          "Repeat the theme unchanged",
          "Ignore the theme",
        ],
        answerIndex: 1,
        explanation: "Recognizability plus transformation is the engine of variation form.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Form Spotting",
        prompt: "Diagram the form of three short pieces you know (folk songs work well): label sections A/B and cadence points.",
      },
      {
        type: "COMPOSITION",
        title: "Small Palace",
        prompt: "Compose a rounded binary piece (16–24 measures): A ending on V, B beginning in contrast and returning to A material to close in I.",
      },
    ],
    skillRewards: { FORM: 35, HARMONY: 10 },
  },
  {
    slug: "countermelody-orchestration-basics",
    title: "Countermelody and Instrument Basics",
    description: "Writing a second voice, and knowing your instruments' ranges.",
    category: "ORCHESTRATION",
    difficulty: 5,
    tierRequirement: "BASIC_COMPOSER",
    order: 20,
    xpReward: 110,
    prerequisiteSlug: "binary-ternary-form",
    content: [
      {
        heading: "The Second Voice",
        body: "A countermelody complements the main line by moving when it rests and resting when it moves — rhythmic interlocking. Prefer contrary or oblique motion; avoid shadowing the melody in parallel octaves, which collapses two voices into one.",
      },
      {
        heading: "Know Your Instruments",
        body: "Every instrument has a range, and within it, sweet spots. Violin shines above middle C; cello sings in its tenor register; flute whispers low and pierces high; horn blends everything. Writing outside an instrument's comfortable range is a choice — make it knowingly.",
        example: "Violin: G3–A7 · Cello: C2–A5 · Flute: C4–D7 · Horn: F2–F5 (sounding)",
      },
    ],
    quiz: [
      {
        subject: "COUNTERPOINT",
        difficulty: 5,
        prompt: "A good countermelody usually:",
        choices: [
          "Copies the melody's rhythm exactly",
          "Moves when the melody rests",
          "Stays on one note",
          "Is always louder",
        ],
        answerIndex: 1,
        explanation: "Interlocking rhythm keeps both lines audible and independent.",
      },
      {
        subject: "COUNTERPOINT",
        difficulty: 5,
        prompt: "Which motion most preserves voice independence?",
        choices: ["Parallel octaves", "Contrary motion", "Unison doubling", "Silence"],
        answerIndex: 1,
        explanation: "Voices moving in opposite directions are heard as truly separate.",
      },
      {
        subject: "FORM",
        difficulty: 5,
        prompt: "The lowest standard note on the cello is:",
        choices: ["G2", "C2", "E2", "A1"],
        answerIndex: 1,
        explanation: "The cello's lowest open string is C2.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Range Check",
        prompt: "From memory, write the practical ranges of violin, cello, flute, and horn; then verify and correct.",
      },
      {
        type: "COMPOSITION",
        title: "Two Voices, One Story",
        prompt: "Take any eight-measure melody you've written and add a countermelody for cello that interlocks rhythmically. Mark every use of contrary motion.",
      },
    ],
    skillRewards: { COUNTERPOINT: 20, INSTRUMENTATION: 20, ORCHESTRATION: 10 },
  },
  {
    slug: "chromatic-harmony-modal-writing",
    title: "Chromatic Harmony and Modal Color",
    description: "Borrowed chords, modal mixture, and the church modes as palettes.",
    category: "HARMONY",
    difficulty: 6,
    tierRequirement: "DECENT_COMPOSER",
    order: 21,
    xpReward: 130,
    prerequisiteSlug: "countermelody-orchestration-basics",
    content: [
      {
        heading: "Borrowing from the Shadow Key",
        body: "Modal mixture borrows chords from the parallel minor: iv, ♭VI, ♭VII in a major key add instant poignancy. The ♭VI–♭VII–I close is a staple of cinematic writing.",
        example: "In C: F minor (iv), A♭ major (♭VI), B♭ major (♭VII).",
      },
      {
        heading: "The Modes as Palettes",
        body: "Dorian (minor with bright 6th), Phrygian (dark ♭2), Lydian (floating ♯4), Mixolydian (major with soft ♭7). Each mode is a ready-made atmosphere; commit to a mode's characteristic note to make the color audible.",
      },
    ],
    quiz: [
      {
        subject: "CHORDS",
        difficulty: 6,
        prompt: "Modal mixture in C major borrows chords from:",
        choices: ["G major", "C minor", "A minor", "F major"],
        answerIndex: 1,
        explanation: "Mixture draws on the parallel minor — C minor.",
      },
      {
        subject: "SCALES",
        difficulty: 6,
        prompt: "Which mode is characterized by a raised 4th degree?",
        choices: ["Dorian", "Phrygian", "Lydian", "Mixolydian"],
        answerIndex: 2,
        explanation: "Lydian's ♯4 gives its floating, luminous quality.",
      },
      {
        subject: "CHORDS",
        difficulty: 6,
        prompt: "The chord ♭VI in C major is:",
        choices: ["A major", "A♭ major", "E♭ major", "F minor"],
        answerIndex: 1,
        explanation: "Lowered 6th degree A♭ carries a major triad: A♭–C–E♭.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Mode Sketches",
        prompt: "Write a two-measure fragment in each of Dorian, Lydian, and Mixolydian on D, making the characteristic note prominent.",
      },
      {
        type: "COMPOSITION",
        title: "Motif Through Three Lenses",
        prompt: "Take one four-note motif and develop it three ways: by inversion, by rhythmic augmentation, and in sequence — within a 16-measure piece that uses at least one borrowed chord.",
      },
    ],
    skillRewards: { HARMONY: 30, EXPRESSION: 15 },
  },
  {
    slug: "counterpoint-species",
    title: "Counterpoint: The Species Approach",
    description: "Two independent voices in disciplined conversation.",
    category: "COUNTERPOINT",
    difficulty: 6,
    tierRequirement: "DECENT_COMPOSER",
    order: 22,
    xpReward: 130,
    prerequisiteSlug: "chromatic-harmony-modal-writing",
    content: [
      {
        heading: "First Species: Note Against Note",
        body: "Against a given melody (cantus firmus), write one note per note. Use consonances (3rds, 6ths, 5ths, octaves), begin and end on perfect consonances, and never move into a perfect 5th or octave in parallel — that destroys independence.",
      },
      {
        heading: "Second and Fourth Species",
        body: "Second species sets two notes against one, admitting passing dissonance on weak beats. Fourth species delays the upper voice to create suspensions — prepared dissonances that resolve down by step. Suspensions are the heartbeat of expressive counterpoint.",
        example: "Suspension formula: preparation (consonant) → suspension (dissonant, tied) → resolution (down a step).",
      },
    ],
    quiz: [
      {
        subject: "COUNTERPOINT",
        difficulty: 6,
        prompt: "Parallel fifths are avoided in counterpoint because they:",
        choices: [
          "Are hard to play",
          "Undermine the independence of the voices",
          "Are dissonant",
          "Are too quiet",
        ],
        answerIndex: 1,
        explanation: "Parallel perfect intervals fuse two voices into one sound.",
      },
      {
        subject: "COUNTERPOINT",
        difficulty: 6,
        prompt: "A suspension resolves:",
        choices: ["Up by leap", "Down by step", "By silence", "Up by step always"],
        answerIndex: 1,
        explanation: "Prepared dissonance resolves downward by step.",
      },
      {
        subject: "COUNTERPOINT",
        difficulty: 6,
        prompt: "In first species counterpoint, dissonances are:",
        choices: ["Required on strong beats", "Not used at all", "Used freely", "Only at the end"],
        answerIndex: 1,
        explanation: "Note-against-note counterpoint is entirely consonant.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "First Species Drill",
        prompt: "Against the cantus C-D-F-E-D-C, write a first-species upper voice. Check every interval.",
      },
      {
        type: "COMPOSITION",
        title: "The Suspended Dialogue",
        prompt: "Write 12 measures of two-voice counterpoint containing at least three suspensions. Any two instruments.",
      },
    ],
    skillRewards: { COUNTERPOINT: 35, HARMONY: 10 },
  },
  {
    slug: "advanced-rhythm-texture",
    title: "Advanced Rhythm and Texture",
    description: "Irregular meters, polyrhythm, and the fabric of sound.",
    category: "RHYTHM",
    difficulty: 7,
    tierRequirement: "DECENT_COMPOSER",
    order: 23,
    xpReward: 130,
    prerequisiteSlug: "counterpoint-species",
    content: [
      {
        heading: "Irregular Meters",
        body: "5/8 and 7/8 group unevenly (2+3, 3+2, 2+2+3 …). The groove comes from committing to a grouping and articulating it consistently — irregular meter is not chaos, it is asymmetric dance.",
      },
      {
        heading: "Polyrhythm and Texture",
        body: "Polyrhythm layers conflicting divisions (3 against 2, 4 against 3). Texture describes the fabric: monophony (one line), homophony (melody + accompaniment), polyphony (independent lines). Great composers modulate texture the way they modulate keys.",
        example: "3:2 — triplets in one hand, duplets in the other, aligning every beat.",
      },
    ],
    quiz: [
      {
        subject: "METER",
        difficulty: 7,
        prompt: "A common grouping of 7/8 is:",
        choices: ["2+2+3", "4+4", "3+3+3", "5+3"],
        answerIndex: 0,
        explanation: "7 eighths split into asymmetric cells like 2+2+3 or 3+2+2.",
      },
      {
        subject: "RHYTHM",
        difficulty: 7,
        prompt: "'Three against two' means:",
        choices: [
          "Triple forte",
          "One voice divides the beat in 3 while another divides it in 2",
          "Three instruments versus two",
          "A 3/2 time signature",
        ],
        answerIndex: 1,
        explanation: "Simultaneous conflicting subdivisions of the same beat.",
      },
      {
        subject: "FORM",
        difficulty: 7,
        prompt: "Melody with chordal accompaniment is which texture?",
        choices: ["Monophony", "Homophony", "Polyphony", "Heterophony"],
        answerIndex: 1,
        explanation: "One dominant line supported by harmony = homophony.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Grouping Workout",
        prompt: "Tap 7/8 as 2+2+3, then 3+2+2, four measures each, accenting group starts. Then tap 3 against 2 slowly.",
      },
      {
        type: "COMPOSITION",
        title: "The Asymmetric Dance",
        prompt: "Compose 16 measures in 5/8 or 7/8 that still feel danceable. Keep one grouping for at least four measures before changing.",
      },
    ],
    skillRewards: { RHYTHM: 35, TECHNIQUE: 10 },
  },
  {
    slug: "fugue-large-form",
    title: "Fugue and Large-Scale Form",
    description: "Subject, answer, episode — and sonata thinking.",
    category: "COUNTERPOINT",
    difficulty: 8,
    tierRequirement: "ADVANCED_COMPOSER",
    order: 24,
    xpReward: 150,
    prerequisiteSlug: "advanced-rhythm-texture",
    content: [
      {
        heading: "The Fugue Machine",
        body: "A fugue grows from one subject. Voices enter in turn — subject in tonic, answer in dominant — against countersubjects. Episodes develop fragments in sequence between subject entries. Devices: inversion, augmentation, diminution, and stretto (overlapping entries) for the climax.",
      },
      {
        heading: "Sonata Thinking",
        body: "Sonata form dramatizes key conflict: exposition presents two themes in opposing keys, development destabilizes them, recapitulation resolves both in the tonic. It is the novel-length architecture of instrumental music.",
        example: "Exposition (I → V) · Development (anywhere) · Recapitulation (I, both themes).",
      },
    ],
    quiz: [
      {
        subject: "FORM",
        difficulty: 8,
        prompt: "In a fugue, the 'answer' is:",
        choices: [
          "The final chord",
          "The subject transposed, usually to the dominant",
          "A rest",
          "The loudest section",
        ],
        answerIndex: 1,
        explanation: "The second voice answers the subject at the fifth.",
      },
      {
        subject: "AUGMENTATION",
        difficulty: 8,
        prompt: "Augmentation transforms a theme by:",
        choices: [
          "Raising its pitch",
          "Doubling its note durations",
          "Adding voices",
          "Removing rests",
        ],
        answerIndex: 1,
        explanation: "Augmentation stretches the theme to longer note values; diminution compresses.",
      },
      {
        subject: "FORM",
        difficulty: 8,
        prompt: "Stretto in a fugue means:",
        choices: [
          "A slow tempo",
          "Subject entries overlapping before the previous finishes",
          "A key change",
          "All voices resting",
        ],
        answerIndex: 1,
        explanation: "Overlapping entries pile up tension — a classic climax device.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Subject Autopsy",
        prompt: "Analyze the subject of any Bach fugue: mark its head motif, its tail, and where the answer enters.",
      },
      {
        type: "COMPOSITION",
        title: "The Two-Voice Invention",
        prompt: "Write a 16–24 measure two-voice invention: state a subject, answer it at the fifth, develop it in one episode using sequence, and close in the tonic.",
      },
    ],
    skillRewards: { COUNTERPOINT: 30, FORM: 25 },
  },
  {
    slug: "virtuoso-writing",
    title: "Writing Virtuoso Repertoire",
    description: "Difficulty that serves music: idiomatic, playable, thrilling.",
    category: "VIRTUOSO",
    difficulty: 9,
    tierRequirement: "VIRTUOSO_REPERTOIRE",
    order: 25,
    xpReward: 180,
    prerequisiteSlug: "fugue-large-form",
    content: [
      {
        heading: "Four Kinds of Difficulty",
        body: "1) Musically effective difficulty: hard AND expressive — the difficulty is the drama. 2) Idiomatic virtuosity: hard but natural to the instrument (fast scales lying under the hand; string crossings that use open strings). 3) Badly written difficulty: hard only because it is awkwardly notated or ignores the instrument. 4) Physically unrealistic writing: impossible reaches, no time to breathe or shift. Aim only for the first two.",
      },
      {
        heading: "The Craft of Playable Fire",
        body: "Rapid passagework should follow scale/arpeggio patterns the hands know. Respect shifting time on strings, breath on winds, and hand span on piano (a 10th is a stretch; an 11th excludes most players). Double stops on violin work in 3rds, 6ths, octaves — check that both notes are reachable on adjacent strings. Endurance: alternate strain with release; even étude writing needs valleys between peaks.",
        example: "Idiomatic: violin passage using open E as pedal between shifted notes. Unrealistic: pianist sustaining a 12th while playing runs in the same hand.",
      },
      {
        heading: "Difficulty With Purpose",
        body: "Ask of every hard passage: what musical effect does the difficulty create — brilliance, fury, weightlessness? If removing the difficulty loses nothing musical, remove it. Virtuosity is theater; the audience must feel the stakes, and the performer must survive the show.",
      },
    ],
    quiz: [
      {
        subject: "COUNTERPOINT",
        difficulty: 9,
        prompt: "Which is the hallmark of IDIOMATIC virtuosity?",
        choices: [
          "Maximum notes per second regardless of layout",
          "Difficulty that fits the instrument's natural patterns",
          "Avoiding all fast passages",
          "Using extreme registers constantly",
        ],
        answerIndex: 1,
        explanation: "Idiomatic writing is hard yet lies naturally under the hands.",
      },
      {
        subject: "FORM",
        difficulty: 9,
        prompt: "A piano passage requiring one hand to span a 13th while running sixteenths is best classified as:",
        choices: [
          "Musically effective difficulty",
          "Idiomatic virtuosity",
          "Physically unrealistic writing",
          "Standard practice",
        ],
        answerIndex: 2,
        explanation: "Beyond nearly all hand spans while moving — unplayable as written.",
      },
      {
        subject: "COUNTERPOINT",
        difficulty: 9,
        prompt: "Violin double stops are most idiomatic in:",
        choices: [
          "2nds and 7ths low on the G string",
          "3rds, 6ths, and octaves on adjacent strings",
          "Any interval anywhere",
          "Unisons only",
        ],
        answerIndex: 1,
        explanation: "3rds, 6ths, octaves on adjacent strings sit under the hand.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Difficulty Audit",
        prompt: "Take a virtuosic passage you admire and classify each hard element: effective, idiomatic, or gratuitous. Justify each label.",
      },
      {
        type: "COMPOSITION",
        title: "The Gauntlet",
        prompt: "Write 32 measures for a solo instrument featuring rapid passagework and at least three contrasting technical sections — each hard for a stated musical reason, each verified playable.",
      },
    ],
    skillRewards: { TECHNIQUE: 40, INSTRUMENTATION: 20, EXPRESSION: 10 },
  },
];
