import type { SeedLesson } from "./types";

// 15 beginner lessons spanning NO_EXPERIENCE → NEW_TO_COMPOSING.

export const beginnerLessons: SeedLesson[] = [
  {
    slug: "what-are-musical-notes",
    title: "What Are Musical Notes?",
    description: "The building blocks of all music: pitch, and how we name it.",
    category: "FUNDAMENTALS",
    difficulty: 1,
    tierRequirement: "NO_EXPERIENCE",
    order: 1,
    xpReward: 50,
    content: [
      {
        heading: "Sound Becomes Music",
        body: "Every sound has a pitch — how high or low it is. Music organizes pitches into notes: named, repeatable pitches that musicians everywhere agree on. When you press a key on a piano or pluck a guitar string, you produce a note.",
      },
      {
        heading: "Naming the Notes",
        body: "Western music uses just seven letter names: A, B, C, D, E, F, G. After G, the pattern repeats — the next A sounds 'the same but higher.' That distance from one note to its repeat is called an octave.",
        example: "A → B → C → D → E → F → G → A (an octave higher)",
      },
      {
        heading: "Why Only Seven?",
        body: "Notes an octave apart vibrate in a 2:1 ratio, so our ears hear them as the same 'note family.' The seven letters describe families of pitch, and the octave tells you which floor of the tower you are on.",
      },
    ],
    quiz: [
      {
        subject: "NOTES",
        difficulty: 1,
        prompt: "How many letter names does Western music use for notes?",
        choices: ["5", "7", "8", "12"],
        answerIndex: 1,
        explanation: "The musical alphabet runs A through G — seven letters — then repeats.",
      },
      {
        subject: "NOTES",
        difficulty: 1,
        prompt: "What comes after G in the musical alphabet?",
        choices: ["H", "A", "G sharp always", "Nothing — it ends"],
        answerIndex: 1,
        explanation: "The alphabet cycles: after G, the pattern begins again at A.",
      },
      {
        subject: "NOTES",
        difficulty: 1,
        prompt: "The distance from one note to the next note of the same name is called:",
        choices: ["A scale", "An octave", "A chord", "A step"],
        answerIndex: 1,
        explanation: "Notes with the same name an 'octave' apart sound like the same note, higher or lower.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Recite the Alphabet Forward and Back",
        prompt: "Starting from C, say the musical alphabet up two octaves and back down. Then start from E and do the same.",
        hint: "C D E F G A B C … remember it wraps after G.",
      },
      {
        type: "COMPOSITION",
        title: "Your First Spell",
        prompt: "Create a four-note melody using only the notes C, D, E, and G. Play or sing it three times. This tiny fragment is your first motif — keep it, you will meet it again.",
        hint: "Try ending on C — notice how 'finished' it feels.",
      },
    ],
    skillRewards: { MELODY: 20 },
  },
  {
    slug: "keyboard-layout",
    title: "The Keyboard Map",
    description: "How the piano keyboard lays out every note in music.",
    category: "FUNDAMENTALS",
    difficulty: 1,
    tierRequirement: "NO_EXPERIENCE",
    order: 2,
    xpReward: 50,
    prerequisiteSlug: "what-are-musical-notes",
    content: [
      {
        heading: "White Keys, Black Keys",
        body: "The piano keyboard is the clearest map of music. The white keys are the seven letter names. The black keys sit in alternating groups of two and three — those groups are your landmarks.",
      },
      {
        heading: "Finding C",
        body: "C is always the white key immediately to the left of any group of two black keys. Find every C and you can find every other note by counting letters.",
        example: "Left of two black keys = C. Left of three black keys = F.",
      },
    ],
    quiz: [
      {
        subject: "NOTES",
        difficulty: 1,
        prompt: "Where is C on the keyboard?",
        choices: [
          "Right of three black keys",
          "Left of a group of two black keys",
          "Between the black keys",
          "It varies by piano",
        ],
        answerIndex: 1,
        explanation: "C always sits just left of the two-black-key group.",
      },
      {
        subject: "NOTES",
        difficulty: 1,
        prompt: "The black keys are arranged in repeating groups of:",
        choices: ["1 and 2", "2 and 3", "3 and 4", "2 and 4"],
        answerIndex: 1,
        explanation: "Groups of two and three black keys alternate all the way up the keyboard.",
      },
      {
        subject: "NOTES",
        difficulty: 1,
        prompt: "Which white key sits immediately left of the three-black-key group?",
        choices: ["C", "E", "F", "B"],
        answerIndex: 2,
        explanation: "F is the landmark to the left of the three black keys.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Landmark Drill",
        prompt: "On a real or virtual keyboard, find all the Cs, then all the Fs, then name every white key in one octave without hesitating.",
      },
      {
        type: "COMPOSITION",
        title: "A Walk on White Keys",
        prompt: "Compose a short melody using only white keys from C to the next C. Start and end on C.",
        hint: "Stepwise motion (moving to neighboring keys) is the easiest way to sound smooth.",
      },
    ],
    skillRewards: { MELODY: 10, TECHNIQUE: 10 },
  },
  {
    slug: "sharps-and-flats",
    title: "Sharps and Flats",
    description: "The black keys, accidentals, and the notes between the letters.",
    category: "FUNDAMENTALS",
    difficulty: 1,
    tierRequirement: "NO_EXPERIENCE",
    order: 3,
    xpReward: 60,
    prerequisiteSlug: "keyboard-layout",
    content: [
      {
        heading: "Between the Letters",
        body: "A sharp (♯) raises a note by a half step; a flat (♭) lowers it by a half step. The black key between C and D can be called C♯ or D♭ — the same sound with two names, chosen by context. These symbols are called accidentals.",
        example: "C♯ = D♭, F♯ = G♭, A♯ = B♭",
      },
      {
        heading: "Two Names, One Key",
        body: "Notes that sound identical but are spelled differently are enharmonic equivalents. Spelling matters: in the key of G, we write F♯, never G♭, so that each letter name appears once in the scale.",
      },
    ],
    quiz: [
      {
        subject: "ACCIDENTALS",
        difficulty: 1,
        prompt: "A sharp (♯) does what to a note?",
        choices: [
          "Lowers it a half step",
          "Raises it a half step",
          "Doubles its length",
          "Makes it louder",
        ],
        answerIndex: 1,
        explanation: "Sharps raise pitch by one half step; flats lower it.",
      },
      {
        subject: "ACCIDENTALS",
        difficulty: 2,
        prompt: "Which note is the enharmonic equivalent of C♯?",
        choices: ["B♭", "D♭", "C♭", "D♯"],
        answerIndex: 1,
        explanation: "C♯ and D♭ are the same key on the piano — the black key between C and D.",
      },
      {
        subject: "ACCIDENTALS",
        difficulty: 2,
        prompt: "Between which pair of white keys is there NO black key?",
        choices: ["C and D", "F and G", "E and F", "G and A"],
        answerIndex: 2,
        explanation: "E–F and B–C are natural half steps: no black key sits between them.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Name the Black Keys",
        prompt: "Name every black key in one octave twice: once using sharps, once using flats.",
      },
      {
        type: "COMPOSITION",
        title: "Shadow Notes",
        prompt: "Write a six-note melody that uses exactly one black key. Listen to how it colors the line.",
        hint: "Try F♯ inside a melody of white keys around G — instant brightness.",
      },
    ],
    skillRewards: { MELODY: 10, HARMONY: 10 },
  },
  {
    slug: "whole-and-half-steps",
    title: "Whole Steps and Half Steps",
    description: "The two smallest distances in music, and why they matter.",
    category: "FUNDAMENTALS",
    difficulty: 1,
    tierRequirement: "NO_EXPERIENCE",
    order: 4,
    xpReward: 60,
    prerequisiteSlug: "sharps-and-flats",
    content: [
      {
        heading: "The Atoms of Melody",
        body: "A half step is the distance between two adjacent keys — black or white. A whole step is two half steps. Every scale, chord, and melody in Western music is built from combinations of these two distances.",
        example: "E→F = half step. C→D = whole step (C♯ lies between).",
      },
      {
        heading: "Hearing the Difference",
        body: "Half steps sound tense and close; whole steps sound open and stable. Composers exploit this: a melody creeping in half steps feels suspenseful, while whole steps feel like confident strides.",
      },
    ],
    quiz: [
      {
        subject: "NOTES",
        difficulty: 1,
        prompt: "A whole step equals how many half steps?",
        choices: ["1", "2", "3", "4"],
        answerIndex: 1,
        explanation: "Two half steps make a whole step.",
      },
      {
        subject: "NOTES",
        difficulty: 2,
        prompt: "Which of these is a half step?",
        choices: ["C to D", "E to F", "F to G", "A to B"],
        answerIndex: 1,
        explanation: "E–F (like B–C) is a natural half step with no key between.",
      },
      {
        subject: "NOTES",
        difficulty: 2,
        prompt: "From G, a whole step up lands on:",
        choices: ["G♯", "A", "A♯", "B"],
        answerIndex: 1,
        explanation: "G → G♯ is a half step; G → A is a whole step.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Step Detective",
        prompt: "For each pair, say whether it is a whole or half step: B–C, D–E, E–F, G–A, C♯–D.",
      },
      {
        type: "COMPOSITION",
        title: "The Creeping Line",
        prompt: "Write two short melodies: one that moves only in half steps, one only in whole steps. Note in one sentence how differently they feel.",
      },
    ],
    skillRewards: { MELODY: 15, HARMONY: 10 },
  },
  {
    slug: "note-values-and-rests",
    title: "Note Values and Rests",
    description: "How long notes last: whole, half, quarter, eighth — and silence.",
    category: "RHYTHM",
    difficulty: 1,
    tierRequirement: "NO_EXPERIENCE",
    order: 5,
    xpReward: 60,
    prerequisiteSlug: "whole-and-half-steps",
    content: [
      {
        heading: "Time Made Visible",
        body: "Notes are not just pitches — they have durations. A whole note lasts four beats, a half note two, a quarter note one, and an eighth note half a beat. Each value is half as long as the one before.",
        example: "𝅝 whole = 2 × 𝅗𝅥 half = 4 × ♩ quarter = 8 × ♪ eighth",
      },
      {
        heading: "Silence Is Music Too",
        body: "Every note value has a matching rest — a measured silence. Rests give music room to breathe; a well-placed rest can be more dramatic than any note.",
      },
    ],
    quiz: [
      {
        subject: "RHYTHM",
        difficulty: 1,
        prompt: "How many quarter notes fit in one whole note?",
        choices: ["2", "3", "4", "8"],
        answerIndex: 2,
        explanation: "A whole note (4 beats) = four quarter notes (1 beat each).",
      },
      {
        subject: "RHYTHM",
        difficulty: 1,
        prompt: "A rest is:",
        choices: [
          "A wrong note",
          "A measured silence",
          "A held note",
          "The end of a piece",
        ],
        answerIndex: 1,
        explanation: "Rests are silences with exact durations, just like notes.",
      },
      {
        subject: "RHYTHM",
        difficulty: 2,
        prompt: "Two eighth notes together last as long as:",
        choices: ["A whole note", "A half note", "A quarter note", "A sixteenth note"],
        answerIndex: 2,
        explanation: "Each eighth is half a beat; two of them make one beat — a quarter note.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Clap the Values",
        prompt: "Clap a steady beat. Against it, clap whole notes, then half notes, then quarters, then eighths — four measures of each.",
      },
      {
        type: "COMPOSITION",
        title: "Rhythm Before Pitch",
        prompt: "Write a four-measure rhythm (no pitches, just durations) that uses at least one rest and at least three different note values.",
      },
    ],
    skillRewards: { RHYTHM: 25 },
  },
  {
    slug: "time-signatures",
    title: "Time Signatures",
    description: "Meters, measures, and the pulse that organizes music.",
    category: "RHYTHM",
    difficulty: 2,
    tierRequirement: "NO_EXPERIENCE",
    order: 6,
    xpReward: 70,
    prerequisiteSlug: "note-values-and-rests",
    content: [
      {
        heading: "The Grid of Time",
        body: "Music groups beats into measures. A time signature tells you two things: the top number is how many beats per measure, the bottom is which note value gets one beat. 4/4 means four quarter-note beats per measure.",
        example: "4/4 = four beats · 3/4 = three beats (a waltz) · 6/8 = two big beats of three",
      },
      {
        heading: "Feel, Not Just Math",
        body: "3/4 lilts, 4/4 marches, 6/8 rolls. The meter is the personality of the pulse. Composers choose meters the way storytellers choose a walking pace.",
      },
    ],
    quiz: [
      {
        subject: "METER",
        difficulty: 1,
        prompt: "In 3/4 time, how many beats are in each measure?",
        choices: ["2", "3", "4", "6"],
        answerIndex: 1,
        explanation: "The top number gives the beats per measure: three.",
      },
      {
        subject: "METER",
        difficulty: 2,
        prompt: "In 6/8, the music usually feels like:",
        choices: [
          "Six equal heavy beats",
          "Two big beats, each dividing into three",
          "Three big beats of two",
          "It has no feel",
        ],
        answerIndex: 1,
        explanation: "6/8 is compound meter: two dotted-quarter pulses, each splitting into three eighths.",
      },
      {
        subject: "METER",
        difficulty: 2,
        prompt: "Which meter is traditionally used for a waltz?",
        choices: ["4/4", "2/4", "3/4", "7/8"],
        answerIndex: 2,
        explanation: "The waltz's ONE-two-three swing is 3/4 time.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Conduct the Meters",
        prompt: "Count aloud and tap: four measures of 4/4, four of 3/4, four of 6/8. Accent beat one each time.",
      },
      {
        type: "COMPOSITION",
        title: "Two Faces of One Melody",
        prompt: "Take your four-note motif from 'Your First Spell' and write it twice: once in 4/4, once in 3/4. Which feels more natural?",
      },
    ],
    skillRewards: { RHYTHM: 25, FORM: 10 },
  },
  {
    slug: "major-scales",
    title: "The Major Scale",
    description: "The most important pattern in music: W-W-H-W-W-W-H.",
    category: "FUNDAMENTALS",
    difficulty: 2,
    tierRequirement: "NO_EXPERIENCE",
    order: 7,
    xpReward: 70,
    prerequisiteSlug: "time-signatures",
    content: [
      {
        heading: "One Pattern, Every Key",
        body: "A major scale is built by stacking steps in a fixed order: Whole, Whole, Half, Whole, Whole, Whole, Half. Start on any note, apply the pattern, and you get that key's major scale.",
        example: "C major: C‑D‑E‑F‑G‑A‑B‑C (the pattern falls entirely on white keys)",
      },
      {
        heading: "Scale Degrees",
        body: "Each note of the scale has a number (1–7) and a job. Degree 1 (the tonic) is home. Degree 5 (the dominant) creates pull back to home. Melodies are journeys away from and back to the tonic.",
      },
    ],
    quiz: [
      {
        subject: "SCALES",
        difficulty: 2,
        prompt: "What is the step pattern of a major scale?",
        choices: ["W-H-W-W-H-W-W", "W-W-H-W-W-W-H", "H-W-W-W-H-W-W", "W-W-W-H-W-W-H"],
        answerIndex: 1,
        explanation: "Whole-Whole-Half-Whole-Whole-Whole-Half defines every major scale.",
      },
      {
        subject: "SCALES",
        difficulty: 2,
        prompt: "The first degree of a scale, the 'home' note, is called the:",
        choices: ["Dominant", "Leading tone", "Tonic", "Mediant"],
        answerIndex: 2,
        explanation: "Scale degree 1 is the tonic — the gravitational center of the key.",
      },
      {
        subject: "SCALES",
        difficulty: 3,
        prompt: "How many sharps does the G major scale contain?",
        choices: ["0", "1", "2", "3"],
        answerIndex: 1,
        explanation: "G major needs F♯ to complete the W-W-H-W-W-W-H pattern.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Build Three Scales",
        prompt: "Using the W-W-H-W-W-W-H pattern, spell the major scales of C, G, and F. Check that each letter name appears exactly once.",
      },
      {
        type: "COMPOSITION",
        title: "Journey Home",
        prompt: "Write an eight-note melody in G major that starts away from G and ends on G. Feel the arrival.",
      },
    ],
    skillRewards: { MELODY: 15, HARMONY: 15 },
  },
  {
    slug: "minor-scales",
    title: "Minor Scales and Mood",
    description: "The darker sibling: natural minor, and why minor sounds sad.",
    category: "FUNDAMENTALS",
    difficulty: 2,
    tierRequirement: "NO_EXPERIENCE",
    order: 8,
    xpReward: 70,
    prerequisiteSlug: "major-scales",
    content: [
      {
        heading: "The Minor Pattern",
        body: "The natural minor scale uses the pattern W-H-W-W-H-W-W. Its lowered third degree is the main source of the 'sad' or 'serious' color we associate with minor keys.",
        example: "A minor: A‑B‑C‑D‑E‑F‑G‑A — all white keys, but a completely different mood than C major.",
      },
      {
        heading: "Relative Keys",
        body: "Every major key has a relative minor that shares its notes: start the same set of pitches from the sixth degree. C major and A minor are relatives — same keys on the piano, different center of gravity.",
      },
    ],
    quiz: [
      {
        subject: "SCALES",
        difficulty: 2,
        prompt: "Which scale degree most defines the minor sound?",
        choices: ["The raised 5th", "The lowered 3rd", "The lowered 1st", "The raised 7th"],
        answerIndex: 1,
        explanation: "The minor (lowered) third darkens the scale's whole character.",
      },
      {
        subject: "SCALES",
        difficulty: 3,
        prompt: "What is the relative minor of C major?",
        choices: ["E minor", "G minor", "A minor", "D minor"],
        answerIndex: 2,
        explanation: "A minor shares all of C major's notes, starting from A — the sixth degree.",
      },
      {
        subject: "SCALES",
        difficulty: 3,
        prompt: "The natural minor step pattern is:",
        choices: ["W-H-W-W-H-W-W", "W-W-H-W-W-W-H", "H-W-W-H-W-W-W", "W-H-W-H-W-H-W"],
        answerIndex: 0,
        explanation: "Whole-Half-Whole-Whole-Half-Whole-Whole builds natural minor.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Major vs Minor Ear Training",
        prompt: "Play (or imagine) C major then A minor scales back to back. Describe the mood difference in your own words.",
      },
      {
        type: "COMPOSITION",
        title: "The Same Song, Darkened",
        prompt: "Take your 'Journey Home' melody and rewrite it in E minor. Keep the rhythm identical; only change the pitches.",
      },
    ],
    skillRewards: { MELODY: 15, EXPRESSION: 15 },
  },
  {
    slug: "basic-intervals",
    title: "Basic Intervals",
    description: "Measuring the distance between notes: 2nds through octaves.",
    category: "FUNDAMENTALS",
    difficulty: 2,
    tierRequirement: "NO_EXPERIENCE",
    order: 9,
    xpReward: 70,
    prerequisiteSlug: "minor-scales",
    content: [
      {
        heading: "Distance Has a Name",
        body: "An interval is the distance between two notes, counted by letter names inclusively. C to E is a third (C, D, E — three letters). C to G is a fifth. Intervals are the vocabulary of harmony.",
        example: "C→D 2nd · C→E 3rd · C→F 4th · C→G 5th · C→C octave",
      },
      {
        heading: "Consonance and Tension",
        body: "Octaves, fifths, and thirds sound stable (consonant). Seconds and sevenths sound tense (dissonant). Music breathes by moving between tension and rest.",
      },
    ],
    quiz: [
      {
        subject: "INTERVALS",
        difficulty: 2,
        prompt: "The interval from C up to G is a:",
        choices: ["3rd", "4th", "5th", "6th"],
        answerIndex: 2,
        explanation: "Count inclusively: C-D-E-F-G = five letters, a fifth.",
      },
      {
        subject: "INTERVALS",
        difficulty: 2,
        prompt: "Which interval is generally considered most consonant?",
        choices: ["Minor 2nd", "Major 7th", "Octave", "Tritone"],
        answerIndex: 2,
        explanation: "The octave is the most stable interval of all.",
      },
      {
        subject: "INTERVALS",
        difficulty: 3,
        prompt: "E up to A is what interval?",
        choices: ["3rd", "4th", "5th", "6th"],
        answerIndex: 1,
        explanation: "E-F-G-A = four letter names: a fourth.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Interval Sprints",
        prompt: "Name the interval for each pair: D→F, G→C, A→E, C→B, F→A.",
      },
      {
        type: "COMPOSITION",
        title: "The Leap and the Step",
        prompt: "Write a melody that alternates steps (2nds) with one dramatic leap of a fifth or larger. Notice how the leap draws attention.",
      },
    ],
    skillRewards: { MELODY: 15, HARMONY: 15 },
  },
  {
    slug: "triads-major-minor",
    title: "Chords: Major and Minor Triads",
    description: "Stacking thirds into the harmonies that carry music.",
    category: "HARMONY",
    difficulty: 2,
    tierRequirement: "NO_EXPERIENCE",
    order: 10,
    xpReward: 80,
    prerequisiteSlug: "basic-intervals",
    content: [
      {
        heading: "Three Notes, One Sound",
        body: "A triad stacks two thirds: root, third, fifth. If the bottom third is major (4 half steps), the triad is major — bright and firm. If it is minor (3 half steps), the triad is minor — shaded and inward.",
        example: "C major: C‑E‑G · C minor: C‑E♭‑G",
      },
      {
        heading: "Chords in a Key",
        body: "Build a triad on every degree of a major scale and you get the key's chord family: I, ii, iii, IV, V, vi, vii°. Almost every song you know moves within one of these families.",
      },
    ],
    quiz: [
      {
        subject: "CHORDS",
        difficulty: 2,
        prompt: "The notes of a C major triad are:",
        choices: ["C-D-E", "C-E-G", "C-F-A", "C-E♭-G"],
        answerIndex: 1,
        explanation: "Root C, major third E, perfect fifth G.",
      },
      {
        subject: "CHORDS",
        difficulty: 2,
        prompt: "What changes a major triad into minor?",
        choices: [
          "Lower the fifth",
          "Lower the third a half step",
          "Raise the root",
          "Add a fourth note",
        ],
        answerIndex: 1,
        explanation: "Only the third moves: E → E♭ turns C major into C minor.",
      },
      {
        subject: "CHORDS",
        difficulty: 3,
        prompt: "In the key of C major, the chord built on the fifth degree (G) is:",
        choices: ["G minor", "G major", "G diminished", "G augmented"],
        answerIndex: 1,
        explanation: "G-B-D uses only C-major notes and forms a major triad — the V chord.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Spell the Family",
        prompt: "Spell all seven triads of C major (C, Dm, Em, F, G, Am, B°) — three notes each.",
      },
      {
        type: "COMPOSITION",
        title: "First Harmony",
        prompt: "Write a melody over the progression C – F – G – C, one chord per measure. Use mostly chord tones on strong beats.",
      },
    ],
    skillRewards: { HARMONY: 25, MELODY: 10 },
  },
  {
    slug: "basic-progressions",
    title: "Basic Chord Progressions",
    description: "I, IV, V and the progressions behind a thousand songs.",
    category: "HARMONY",
    difficulty: 3,
    tierRequirement: "NO_EXPERIENCE",
    order: 11,
    xpReward: 80,
    prerequisiteSlug: "triads-major-minor",
    content: [
      {
        heading: "The Three Pillars",
        body: "I is home, IV moves away, V demands return. The progression I–IV–V–I is the skeleton of folk, rock, classical, and hymn traditions alike. Learn to hear each chord's role, not just its name.",
        example: "In C: C (I) → F (IV) → G (V) → C (I)",
      },
      {
        heading: "Adding vi",
        body: "The vi chord (A minor in C) borrows minor shading inside a major key. I–vi–IV–V is the classic '50s progression'; I–V–vi–IV powers half of modern pop.",
      },
    ],
    quiz: [
      {
        subject: "FUNCTIONS",
        difficulty: 3,
        prompt: "Which chord creates the strongest pull back to I?",
        choices: ["ii", "IV", "V", "vi"],
        answerIndex: 2,
        explanation: "V (the dominant) contains the leading tone, which strains upward to the tonic.",
      },
      {
        subject: "FUNCTIONS",
        difficulty: 3,
        prompt: "In the key of G major, the IV chord is:",
        choices: ["C major", "D major", "E minor", "A minor"],
        answerIndex: 0,
        explanation: "The fourth degree of G major is C; its triad is C major.",
      },
      {
        subject: "FUNCTIONS",
        difficulty: 3,
        prompt: "The progression I–V–vi–IV in C major is:",
        choices: ["C–G–Am–F", "C–F–G–C", "C–Am–F–G", "C–Dm–G–C"],
        answerIndex: 0,
        explanation: "I=C, V=G, vi=Am, IV=F.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Transpose the Pillars",
        prompt: "Write out I–IV–V–I in the keys of C, G, D, and F major.",
      },
      {
        type: "COMPOSITION",
        title: "Song Skeleton",
        prompt: "Compose eight measures over I–vi–IV–V repeated twice. Give the second phrase a higher melodic peak than the first.",
      },
    ],
    skillRewards: { HARMONY: 25, FORM: 10 },
  },
  {
    slug: "melody-writing",
    title: "Melody Writing Fundamentals",
    description: "Shape, contour, and what makes a line memorable.",
    category: "MELODY",
    difficulty: 3,
    tierRequirement: "NEW_TO_COMPOSING",
    order: 12,
    xpReward: 90,
    prerequisiteSlug: "basic-progressions",
    content: [
      {
        heading: "Contour Is Character",
        body: "A melody is a shape in time: rising lines build energy, falling lines release it, arches feel complete. Great melodies usually have one clear high point — the climax — placed late in the phrase.",
      },
      {
        heading: "Steps, Leaps, and Balance",
        body: "Mostly stepwise motion keeps a line singable; an occasional leap adds drama. A classic rule of thumb: after a large leap, step back in the opposite direction to restore balance.",
        example: "C‑D‑E‑F‑G‑(leap)‑C‑B‑A‑G: the leap up is answered by steps down.",
      },
    ],
    quiz: [
      {
        subject: "NOTES",
        difficulty: 3,
        prompt: "Where does the climax of a well-shaped phrase usually sit?",
        choices: ["The first note", "Near the end, before the resolution", "Exactly halfway", "Melodies should avoid climaxes"],
        answerIndex: 1,
        explanation: "A late high point gives a phrase direction and payoff.",
      },
      {
        subject: "NOTES",
        difficulty: 3,
        prompt: "After a large upward leap, a melody usually sounds best if it:",
        choices: ["Leaps again upward", "Steps down", "Stops", "Repeats the leap"],
        answerIndex: 1,
        explanation: "Stepwise motion in the opposite direction rebalances the line.",
      },
      {
        subject: "NOTES",
        difficulty: 3,
        prompt: "Which motion keeps a melody most singable?",
        choices: ["Constant large leaps", "Mostly stepwise motion", "Repeating one note", "Random chromatic jumps"],
        answerIndex: 1,
        explanation: "Steps are easy to sing and hear; leaps are spice, not the meal.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Contour Sketching",
        prompt: "Draw the contour (just the up/down shape) of three melodies you love. Mark each climax.",
      },
      {
        type: "COMPOSITION",
        title: "The Arch",
        prompt: "Write an eight-measure melody with a single climax in measure 6. Use mostly steps and exactly two leaps.",
      },
    ],
    skillRewards: { MELODY: 30, EXPRESSION: 10 },
  },
  {
    slug: "phrases-question-answer",
    title: "Phrases: Question and Answer",
    description: "Antecedent and consequent — the sentence structure of music.",
    category: "MELODY",
    difficulty: 3,
    tierRequirement: "NEW_TO_COMPOSING",
    order: 13,
    xpReward: 90,
    prerequisiteSlug: "melody-writing",
    content: [
      {
        heading: "Music Speaks in Sentences",
        body: "A musical phrase is like a clause of speech, typically four measures. Pair two phrases so the first ends unresolved (often on the dominant) and the second answers by resolving to the tonic: a question and its answer.",
        example: "Antecedent: ends on V (comma). Consequent: ends on I (period).",
      },
      {
        heading: "The Period",
        body: "This question-answer pair is called a period. Both phrases usually begin the same way, then diverge at their endings — familiarity plus resolution.",
      },
    ],
    quiz: [
      {
        subject: "FORM",
        difficulty: 3,
        prompt: "An antecedent phrase typically ends:",
        choices: ["On the tonic, resolved", "On the dominant, unresolved", "With silence", "With a key change"],
        answerIndex: 1,
        explanation: "The 'question' ends off-balance — usually a half cadence on V.",
      },
      {
        subject: "FORM",
        difficulty: 3,
        prompt: "A period is:",
        choices: [
          "A single long note",
          "A question phrase paired with an answer phrase",
          "Any eight measures",
          "A type of chord",
        ],
        answerIndex: 1,
        explanation: "Antecedent + consequent = period.",
      },
      {
        subject: "CADENCES",
        difficulty: 3,
        prompt: "A phrase ending V→I is called a(n):",
        choices: ["Half cadence", "Deceptive cadence", "Authentic cadence", "Plagal cadence"],
        answerIndex: 2,
        explanation: "Dominant resolving to tonic is the authentic cadence — music's period mark.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Find the Question",
        prompt: "Hum 'Twinkle Twinkle' — identify where the question ends and the answer begins.",
      },
      {
        type: "COMPOSITION",
        title: "The First Motif",
        prompt: "Write a four-measure melody (the question). Then repeat the main idea but change the ending so it resolves home (the answer). Eight measures total.",
      },
    ],
    skillRewards: { MELODY: 20, FORM: 20 },
  },
  {
    slug: "motifs-repetition-variation",
    title: "Motifs, Repetition, and Variation",
    description: "How tiny ideas grow into whole pieces.",
    category: "MELODY",
    difficulty: 3,
    tierRequirement: "NEW_TO_COMPOSING",
    order: 14,
    xpReward: 90,
    prerequisiteSlug: "phrases-question-answer",
    content: [
      {
        heading: "The Seed",
        body: "A motif is a short, distinctive fragment — often just three to five notes. Beethoven's Fifth grows almost entirely from four notes. A strong motif is rhythmically distinctive, not just a pretty pitch sequence.",
      },
      {
        heading: "Repeat, Then Change",
        body: "Repetition makes an idea memorable; variation keeps it alive. Classic variation tools: transpose it (sequence), change its rhythm, invert its direction, or extend its ending. Repeat exactly at most twice — the third time, transform.",
        example: "Motif: G-G-A-B. Sequence up: A-A-B-C. Inverted: G-G-F-E.",
      },
    ],
    quiz: [
      {
        subject: "FORM",
        difficulty: 3,
        prompt: "A motif is best described as:",
        choices: [
          "A complete melody",
          "A short, distinctive musical fragment",
          "A chord progression",
          "A type of scale",
        ],
        answerIndex: 1,
        explanation: "Motifs are small memorable cells that pieces grow from.",
      },
      {
        subject: "FORM",
        difficulty: 3,
        prompt: "Repeating a motif starting on a different pitch is called a:",
        choices: ["Cadence", "Sequence", "Rest", "Modulation"],
        answerIndex: 1,
        explanation: "A sequence restates the idea higher or lower.",
      },
      {
        subject: "FORM",
        difficulty: 4,
        prompt: "Inverting a motif means:",
        choices: [
          "Playing it backward",
          "Flipping its intervals upside down",
          "Playing it twice as fast",
          "Playing it louder",
        ],
        answerIndex: 1,
        explanation: "Inversion mirrors the contour: rising intervals fall, falling intervals rise.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Transform Drill",
        prompt: "Take the motif C-E-D-G. Write its sequence a step higher, its inversion, and a rhythmic variation.",
      },
      {
        type: "COMPOSITION",
        title: "One Seed, One Garden",
        prompt: "Compose eight measures grown entirely from ONE motif using at least three different transformations. Label each transformation in your notes.",
      },
    ],
    skillRewards: { MELODY: 20, FORM: 15, EXPRESSION: 5 },
  },
  {
    slug: "cadences-and-accompaniment",
    title: "Cadences and Basic Accompaniment",
    description: "How phrases end, and how to support a melody with texture.",
    category: "HARMONY",
    difficulty: 3,
    tierRequirement: "NEW_TO_COMPOSING",
    order: 15,
    xpReward: 90,
    prerequisiteSlug: "motifs-repetition-variation",
    content: [
      {
        heading: "Punctuation Marks",
        body: "Cadences are harmonic punctuation. Authentic (V–I): a period. Half (ending on V): a comma. Plagal (IV–I): the 'Amen' softening. Deceptive (V–vi): a plot twist — you expected home and got somewhere bittersweet.",
      },
      {
        heading: "Beneath the Melody",
        body: "Basic accompaniment patterns: block chords (solid, hymn-like), broken chords / Alberti bass (flowing motion), and arpeggios (harp-like sweep). The accompaniment should support, not compete with, the melody.",
        example: "Alberti bass on C major: C‑G‑E‑G, C‑G‑E‑G …",
      },
    ],
    quiz: [
      {
        subject: "CADENCES",
        difficulty: 3,
        prompt: "A deceptive cadence typically moves:",
        choices: ["V to I", "V to vi", "IV to I", "I to V"],
        answerIndex: 1,
        explanation: "V→vi promises resolution then sidesteps it — the musical plot twist.",
      },
      {
        subject: "CADENCES",
        difficulty: 3,
        prompt: "The plagal cadence is:",
        choices: ["V–I", "IV–I", "ii–V", "V–vi"],
        answerIndex: 1,
        explanation: "IV–I, famous as the 'Amen' cadence in hymns.",
      },
      {
        subject: "CHORDS",
        difficulty: 3,
        prompt: "Alberti bass is a pattern of:",
        choices: [
          "Repeated block chords",
          "Broken chord figures (low-high-middle-high)",
          "Octave leaps",
          "Drum rhythms",
        ],
        answerIndex: 1,
        explanation: "Alberti bass animates a chord as low-high-middle-high broken figures.",
      },
    ],
    exercises: [
      {
        type: "PRACTICE",
        title: "Cadence Tasting",
        prompt: "Write (or play) the same two-measure phrase four times, ending with each cadence type: authentic, half, plagal, deceptive.",
      },
      {
        type: "COMPOSITION",
        title: "Melody Meets Accompaniment",
        prompt: "Take your 'First Motif' period and add an accompaniment: block chords for the question, broken chords for the answer. End with an authentic cadence.",
      },
    ],
    skillRewards: { HARMONY: 25, EXPRESSION: 10, INSTRUMENTATION: 5 },
  },
];
