// Dungeon world seed data: areas, rooms, bosses, artifacts, achievements,
// specializations, challenge components.

export const artifacts = [
  {
    key: "ancient-motif",
    name: "Ancient Motif",
    description: "A fragment of melody older than memory. Its bearer may reshape fate itself.",
    rarity: "UNCOMMON",
    icon: "📜",
    effect: "REROLL",
    unlockMethod: "Found in the Treasure Vault of the Hall of Melody.",
  },
  {
    key: "quill-of-inspiration",
    name: "Quill of Inspiration",
    description: "A raven's feather that never runs dry. Words and notes flow faster while it is held.",
    rarity: "RARE",
    icon: "🪶",
    effect: "BONUS_XP",
    unlockMethod: "Awarded for a 7-day Creative Flame streak.",
  },
  {
    key: "chromatic-crystal",
    name: "Chromatic Crystal",
    description: "Light bends into twelve colors inside this stone — one for every note of the scale.",
    rarity: "EPIC",
    icon: "💎",
    effect: "UNLOCK_HARMONY",
    unlockMethod: "Reward for defeating the Chromatic Serpent.",
  },
  {
    key: "eye-of-the-virtuoso",
    name: "Eye of the Virtuoso",
    description: "It sees every fingering, every shift, every impossible passage — and finds the possible one.",
    rarity: "EPIC",
    icon: "👁️",
    effect: "UNLOCK_VIRTUOSO",
    unlockMethod: "Reward for defeating the Iron Metronome.",
  },
  {
    key: "candle-of-the-forgotten-composer",
    name: "Candle of the Forgotten Composer",
    description: "Its flame reveals music that was never written down. Rare challenges appear in its light.",
    rarity: "LEGENDARY",
    icon: "🕯️",
    effect: "REVEAL_CHALLENGE",
    unlockMethod: "Awarded for a 30-day Creative Flame streak.",
  },
  {
    key: "bell-of-the-nave",
    name: "Bell of the Nave",
    description: "A bronze bell from the Cathedral's fallen tower. It tolls only for true cadences.",
    rarity: "RARE",
    icon: "🔔",
    effect: "COSMETIC",
    unlockMethod: "Found in the Cathedral of Composition.",
  },
  {
    key: "hourglass-of-rest",
    name: "Hourglass of Rest",
    description: "Sand that flows upward, returning a lost day to the flame.",
    rarity: "UNCOMMON",
    icon: "⏳",
    effect: "REST_DAY",
    unlockMethod: "Found in the Rest Chamber of the Tower of Rhythm.",
  },
  {
    key: "mask-of-the-maestro",
    name: "Mask of the Maestro",
    description: "Worn by the Forgotten Composer in life. It hums a theme no one alive remembers.",
    rarity: "LEGENDARY",
    icon: "🎭",
    effect: "COSMETIC",
    unlockMethod: "Defeat The Forgotten Composer.",
  },
];

export const bosses = [
  {
    key: "chromatic-serpent",
    name: "The Chromatic Serpent",
    title: "Coiled Guardian of the Crypt",
    description:
      "A serpent whose scales are the twelve tones. It slithers between keys, and only a composer who can follow it through every modulation may strike it down.",
    artwork: "🐍",
    totalHp: 10000,
    difficulty: 5,
    levelRequirement: 5,
    xpReward: 800,
    rewardArtifactKey: "chromatic-crystal",
    phases: [
      { order: 1, name: "The Coiling", description: "Compose in A minor. The Serpent circles, testing your diatonic footing.", hpThresholdPercent: 100 },
      { order: 2, name: "The Shedding", description: "At 70% HP the Serpent sheds its key: shift your material to C-sharp minor.", hpThresholdPercent: 70 },
      { order: 3, name: "The Strike", description: "At 35% HP it lunges: increase the rhythmic difficulty of your passage.", hpThresholdPercent: 35 },
      { order: 4, name: "The Binding", description: "Combine your original theme with a transformed version to bind the Serpent.", hpThresholdPercent: 15 },
    ],
    objectives: [
      { name: "Complete a modulation", description: "Modulate convincingly between two keys using a pivot chord.", damage: 1000, bonus: false, finalBlow: false, order: 1 },
      { name: "Create a chromatic sequence", description: "Write a sequence whose steps descend or ascend chromatically.", damage: 1500, bonus: false, finalBlow: false, order: 2 },
      { name: "Use an original motif", description: "Base your material on a motif of your own invention.", damage: 2000, bonus: false, finalBlow: false, order: 3 },
      { name: "Avoid parallel fifths", description: "Keep your voice leading clean throughout.", damage: 500, bonus: true, finalBlow: false, order: 4 },
      { name: "Complete the final composition", description: "Deliver the finished piece that fulfills all phases.", damage: 5000, bonus: false, finalBlow: true, order: 5 },
    ],
  },
  {
    key: "iron-metronome",
    name: "The Iron Metronome",
    title: "Tyrant of the Tower",
    description:
      "An iron colossus that ticks without mercy. Every irregular beat you master loosens a gear; every rushed passage feeds it.",
    artwork: "⚙️",
    totalHp: 8000,
    difficulty: 4,
    levelRequirement: 4,
    xpReward: 650,
    rewardArtifactKey: "eye-of-the-virtuoso",
    phases: [
      { order: 1, name: "The Tick", description: "Compose in strict 4/4 — prove you can keep perfect time before you break it.", hpThresholdPercent: 100 },
      { order: 2, name: "The Slip", description: "At 60% HP the mechanism slips: shift your material into 7/8.", hpThresholdPercent: 60 },
      { order: 3, name: "The Overwind", description: "At 25% HP it overwinds: set two rhythmic layers against each other.", hpThresholdPercent: 25 },
    ],
    objectives: [
      { name: "Write a syncopated passage", description: "Eight measures where accents consistently fall off the beat.", damage: 1200, bonus: false, finalBlow: false, order: 1 },
      { name: "Master an irregular meter", description: "Compose a passage in 5/8 or 7/8 with a consistent grouping.", damage: 1800, bonus: false, finalBlow: false, order: 2 },
      { name: "Layer a polyrhythm", description: "Set 3 against 2 (or bolder) between two voices.", damage: 1500, bonus: false, finalBlow: false, order: 3 },
      { name: "Keep a motiv identical across meters", description: "State the same motif in two different meters without losing its identity.", damage: 500, bonus: true, finalBlow: false, order: 4 },
      { name: "Complete the final composition", description: "Deliver the finished rhythmic study.", damage: 3000, bonus: false, finalBlow: true, order: 5 },
    ],
  },
  {
    key: "pale-soprano",
    name: "The Pale Soprano",
    title: "Voice of the Frozen Hall",
    description:
      "A spectral singer whose single unbroken line freezes all who cannot answer it. Only true melody — shaped, breathing, inevitable — can thaw her sorrow.",
    artwork: "🎤",
    totalHp: 6000,
    difficulty: 3,
    levelRequirement: 3,
    xpReward: 500,
    rewardArtifactKey: null,
    phases: [
      { order: 1, name: "The Lament", description: "She sings a falling phrase. Answer with a melody in a minor key.", hpThresholdPercent: 100 },
      { order: 2, name: "The Echo", description: "At 50% HP she echoes you. Develop your own phrase by variation.", hpThresholdPercent: 50 },
    ],
    objectives: [
      { name: "Shape a climax", description: "Write a phrase with a single clear climax placed late.", damage: 1500, bonus: false, finalBlow: false, order: 1 },
      { name: "Write a question and answer", description: "A period: antecedent ending on V, consequent resolving to I.", damage: 1500, bonus: false, finalBlow: false, order: 2 },
      { name: "Balance a leap", description: "Follow every leap of a fifth or more with contrary stepwise motion.", damage: 500, bonus: true, finalBlow: false, order: 3 },
      { name: "Complete the final composition", description: "Deliver the finished melody for voice or solo instrument.", damage: 2500, bonus: false, finalBlow: true, order: 4 },
    ],
  },
  {
    key: "forgotten-composer",
    name: "The Forgotten Composer",
    title: "Final Echo of the Cathedral",
    description:
      "Beneath the Cathedral sleeps the one who built the Dungeon — a master erased from history. The encounter is a symphony in five movements, and its final page must be written by you.",
    artwork: "🎭",
    totalHp: 25000,
    difficulty: 10,
    levelRequirement: 20,
    xpReward: 3000,
    final: true,
    rewardArtifactKey: "mask-of-the-maestro",
    phases: [
      { order: 1, name: "Movement I — The Summons", description: "Melody. Present a theme worthy of a symphony's first page.", hpThresholdPercent: 100 },
      { order: 2, name: "Movement II — The Descent", description: "Harmony. At 80% HP: darken your theme with mixture and chromaticism.", hpThresholdPercent: 80 },
      { order: 3, name: "Movement III — The Machine", description: "Rhythm. At 60% HP: drive the theme through irregular meter.", hpThresholdPercent: 60 },
      { order: 4, name: "Movement IV — The Mirror", description: "Counterpoint. At 40% HP: set the theme against its own inversion.", hpThresholdPercent: 40 },
      { order: 5, name: "Movement V — The Naming", description: "Form. At 20% HP: bind all movements into one final architecture.", hpThresholdPercent: 20 },
    ],
    objectives: [
      { name: "Resurrect an early motif", description: "Take a motif you created earlier in your journey and make it the seed of this work.", damage: 4000, bonus: false, finalBlow: false, order: 1 },
      { name: "Modulate through three keys", description: "Travel through at least three tonal centers and return home.", damage: 4000, bonus: false, finalBlow: false, order: 2 },
      { name: "Write a contrapuntal section", description: "At least eight measures of genuine two-voice (or more) counterpoint.", damage: 4000, bonus: false, finalBlow: false, order: 3 },
      { name: "Command an irregular meter", description: "One section in 5/8, 7/8, or mixed meter.", damage: 3000, bonus: false, finalBlow: false, order: 4 },
      { name: "Close without cliché", description: "A final cadence that feels inevitable without a plain V–I.", damage: 2000, bonus: true, finalBlow: false, order: 5 },
      { name: "Complete the capstone composition", description: "Deliver the finished multi-section work — your name against the silence.", damage: 8000, bonus: false, finalBlow: true, order: 6 },
    ],
  },
];

export interface SeedRoom {
  name: string;
  description: string;
  type: string;
  order: number;
  levelRequirement?: number;
  bossKey?: string;
  artifactKey?: string;
  puzzleData?: object;
}

export const dungeonAreas: {
  key: string;
  name: string;
  description: string;
  theme: string;
  icon: string;
  levelRequirement: number;
  tierRequirement: string;
  skillKey: string | null;
  order: number;
  special?: boolean;
  rooms: SeedRoom[];
}[] = [
  {
    key: "hall-of-melody",
    name: "Hall of Melody",
    description: "Marble corridors that hum your own tunes back at you, slightly changed.",
    theme: "Where every echo is a variation.",
    icon: "🏛️",
    levelRequirement: 1,
    tierRequirement: "NO_EXPERIENCE",
    skillKey: "MELODY",
    order: 1,
    rooms: [
      { name: "The Echoing Steps", description: "A first trial of pure line.", type: "CHALLENGE", order: 1 },
      {
        name: "The Shattered Phrase",
        description: "Fragments of a melody lie scattered. Restore their order.",
        type: "PUZZLE",
        order: 2,
        puzzleData: {
          kind: "ARRANGE",
          prompt: "A four-part phrase has been shattered. Arrange the fragments into a musical sentence: statement, repetition, departure, resolution.",
          pieces: [
            { id: "a", label: "Opening motif on the tonic (statement)" },
            { id: "b", label: "The motif repeated a step higher (repetition)" },
            { id: "c", label: "A rising sequence building tension (departure)" },
            { id: "d", label: "A falling line cadencing on the tonic (resolution)" },
          ],
          solution: ["a", "b", "c", "d"],
          explanation: "Statement–repetition–departure–resolution is the classic 'sentence' structure of melodic phrases.",
        },
      },
      {
        name: "Vault of the Ancient Motif",
        description: "Something old and small glows on a pedestal.",
        type: "TREASURE",
        order: 3,
        levelRequirement: 2,
        artifactKey: "ancient-motif",
      },
      { name: "Chamber of the Unrepeatable", description: "A curse forbids exact repetition.", type: "CURSE", order: 4, levelRequirement: 2 },
      { name: "The Soprano's Stage", description: "A pale figure waits in the cold light.", type: "BOSS", order: 5, levelRequirement: 3, bossKey: "pale-soprano" },
    ],
  },
  {
    key: "crypt-of-harmony",
    name: "Crypt of Harmony",
    description: "Stacked sarcophagi resonate in thirds when you speak.",
    theme: "The dead sing in chords here.",
    icon: "⚰️",
    levelRequirement: 3,
    tierRequirement: "NO_EXPERIENCE",
    skillKey: "HARMONY",
    order: 2,
    rooms: [
      { name: "The Resonant Ossuary", description: "Bones hum the chord families of every key.", type: "CHALLENGE", order: 1 },
      {
        name: "The Missing Tombstone",
        description: "One chord has been stolen from the progression carved into the wall.",
        type: "PUZZLE",
        order: 2,
        puzzleData: {
          kind: "MULTIPLE_CHOICE",
          prompt: "Carved into the crypt wall: C – Am – ? – G7 – C. The missing chord prepares the dominant. Which stone completes the inscription?",
          choices: ["E major", "Dm (the ii chord)", "B diminished", "C7"],
          answerIndex: 1,
          explanation: "ii (Dm) is the classic predominant, setting up G7 → C.",
        },
      },
      { name: "Chamber of Silence", description: "The tonic is forbidden until the final measure.", type: "CURSE", order: 3, levelRequirement: 4 },
      { name: "The Serpent's Coil", description: "Scales glitter in twelve colors ahead.", type: "BOSS", order: 4, levelRequirement: 5, bossKey: "chromatic-serpent" },
    ],
  },
  {
    key: "tower-of-rhythm",
    name: "Tower of Rhythm",
    description: "Every stair lands on a different subdivision. Do not trip.",
    theme: "The Tower ticks. Climb in time.",
    icon: "🗼",
    levelRequirement: 2,
    tierRequirement: "NO_EXPERIENCE",
    skillKey: "RHYTHM",
    order: 3,
    rooms: [
      { name: "The Stair of Subdivisions", description: "Climb from whole notes to sixteenths.", type: "CHALLENGE", order: 1 },
      {
        name: "The Jammed Clockwork",
        description: "The tower's great clock has lost a gear pattern.",
        type: "PUZZLE",
        order: 2,
        puzzleData: {
          kind: "MULTIPLE_CHOICE",
          prompt: "The clock's measure holds exactly one 4/4 bar: quarter note + eighth note + ? + quarter note. Which gear completes the measure?",
          choices: ["A half note", "A dotted quarter note", "An eighth note", "A whole note"],
          answerIndex: 1,
          explanation: "1 + 0.5 + 1.5 + 1 = 4 beats: the dotted quarter completes the bar.",
        },
      },
      { name: "Rest Chamber of the Hourglass", description: "A quiet floor where the ticking cannot reach.", type: "REST", order: 3, artifactKey: "hourglass-of-rest" },
      { name: "The Pendulum Throne", description: "The Iron Metronome ticks above.", type: "BOSS", order: 4, levelRequirement: 4, bossKey: "iron-metronome" },
    ],
  },
  {
    key: "hall-of-the-virtuoso",
    name: "Hall of the Virtuoso",
    description: "Portraits of great performers watch your fingering with narrowed eyes.",
    theme: "Play what cannot be played. Then prove it can.",
    icon: "🎻",
    levelRequirement: 8,
    tierRequirement: "DECENT_COMPOSER",
    skillKey: "TECHNIQUE",
    order: 4,
    rooms: [
      { name: "Gallery of Passagework", description: "Runs and arpeggios coil along the walls.", type: "CHALLENGE", order: 1 },
      {
        name: "The Impossible Manuscript",
        description: "A score on the lectern kills its performers. Find the flaw.",
        type: "PUZZLE",
        order: 2,
        puzzleData: {
          kind: "MULTIPLE_CHOICE",
          prompt: "The cursed score demands a pianist hold a sustained 12th in one hand while the same hand plays continuous sixteenth-note runs. What is the flaw?",
          choices: [
            "The key is too hard",
            "One hand cannot both sustain a wide interval and run passagework — physically unrealistic writing",
            "Sixteenth notes are too fast for piano",
            "There is no flaw",
          ],
          answerIndex: 1,
          explanation: "A hand cannot stretch a 12th AND move freely: unrealistic writing, not virtuosity.",
        },
      },
      { name: "Chamber of the Left Hand", description: "The lesser hand must lead.", type: "CURSE", order: 3, levelRequirement: 9 },
    ],
  },
  {
    key: "ancient-conservatory",
    name: "Ancient Conservatory",
    description: "Dust-covered practice rooms where fugues still argue with themselves.",
    theme: "The old rules live here, and they are watching.",
    icon: "🏚️",
    levelRequirement: 10,
    tierRequirement: "DECENT_COMPOSER",
    skillKey: "COUNTERPOINT",
    order: 5,
    special: true,
    rooms: [
      { name: "The Species Cells", description: "Note against note, until you earn a second.", type: "CHALLENGE", order: 1 },
      {
        name: "The Broken Fugue",
        description: "A fugue lies dismembered on the floor. Name its parts to restore it.",
        type: "PUZZLE",
        order: 2,
        puzzleData: {
          kind: "MULTIPLE_CHOICE",
          prompt: "In the broken fugue, the subject reappears with every interval flipped — rising steps now fall, falling leaps now rise. Which transformation is this?",
          choices: ["Retrograde", "Inversion", "Augmentation", "Diminution"],
          answerIndex: 1,
          explanation: "Inversion mirrors the contour; retrograde reverses the order; augmentation/diminution change durations.",
        },
      },
      { name: "The Mirrored Cloister", description: "Compose against your own inversion.", type: "CURSE", order: 3, levelRequirement: 12 },
    ],
  },
  {
    key: "impressionist-gardens",
    name: "Impressionist Gardens",
    description: "Fountains blur every reflection; the hedges are planted in whole tones.",
    theme: "Nothing resolves here. That is the point.",
    icon: "🌫️",
    levelRequirement: 8,
    tierRequirement: "BASIC_COMPOSER",
    skillKey: "EXPRESSION",
    order: 6,
    special: true,
    rooms: [
      { name: "The Whole-Tone Pond", description: "Six stones cross the water, all equally spaced.", type: "CHALLENGE", order: 1 },
      {
        name: "The Veiled Statue",
        description: "A statue hums a scale with no half steps at all.",
        type: "PUZZLE",
        order: 2,
        puzzleData: {
          kind: "MULTIPLE_CHOICE",
          prompt: "The statue's scale divides the octave into six equal whole steps, erasing any sense of leading tone. Which scale is it?",
          choices: ["Harmonic minor", "The whole-tone scale", "Dorian mode", "The chromatic scale"],
          answerIndex: 1,
          explanation: "The whole-tone scale — a signature Impressionist color with no half-step gravity.",
        },
      },
      { name: "Garden of Endless Dusk", description: "Traditional cadences wilt at the gate.", type: "CURSE", order: 3, levelRequirement: 9 },
    ],
  },
  {
    key: "frozen-conservatory",
    name: "The Frozen Conservatory",
    description: "A music school flash-frozen mid-recital. The silence has texture.",
    theme: "Sparse. Cold. Every note must earn its warmth.",
    icon: "❄️",
    levelRequirement: 12,
    tierRequirement: "DECENT_COMPOSER",
    skillKey: "EXPRESSION",
    order: 7,
    special: true,
    rooms: [
      { name: "The Frostbitten Recital Hall", description: "Compose with almost nothing: sparse texture, minor keys, echo.", type: "CHALLENGE", order: 1 },
      { name: "The Frozen Choir Loft", description: "Voices hang in the air, waiting decades between entrances.", type: "CHALLENGE", order: 2 },
      { name: "Hearth of the Last Ember", description: "One warm room. The flame remembers you.", type: "REST", order: 3 },
    ],
  },
  {
    key: "inferno-of-virtuosity",
    name: "The Inferno of Virtuosity",
    description: "Descending galleries of fire where tempo only rises.",
    theme: "Speed, endurance, and no apologies.",
    icon: "🔥",
    levelRequirement: 15,
    tierRequirement: "ADVANCED_COMPOSER",
    skillKey: "TECHNIQUE",
    order: 8,
    special: true,
    rooms: [
      { name: "The First Circle: Passagework", description: "Rapid scales that must remain musical.", type: "CHALLENGE", order: 1 },
      { name: "The Second Circle: Endurance", description: "Long-form technical writing with peaks and valleys.", type: "CHALLENGE", order: 2 },
      { name: "The Third Circle: Coordination", description: "Two hands, two meters, one player.", type: "CURSE", order: 3, levelRequirement: 17 },
    ],
  },
  {
    key: "cathedral-of-composition",
    name: "Cathedral of Composition",
    description: "The endgame. Every skill you own is a stone in this vault.",
    theme: "Here your whole journey is the instrument.",
    icon: "⛪",
    levelRequirement: 20,
    tierRequirement: "ADVANCED_COMPOSER",
    skillKey: "FORM",
    order: 9,
    rooms: [
      { name: "Ashes of the Choir", description: "Write a choral texture using only open intervals — fourths, fifths, octaves.", type: "CHALLENGE", order: 1 },
      { name: "The Collapsing Nave", description: "Start with a stable theme and gradually destroy it through chromatic alteration.", type: "CHALLENGE", order: 2 },
      { name: "The Final Bell", description: "Create a final cadence that feels inevitable without a traditional V–I.", type: "CHALLENGE", order: 3 },
      { name: "Reliquary of the Bell", description: "The Cathedral rewards those who reach its heart.", type: "TREASURE", order: 4, artifactKey: "bell-of-the-nave" },
      { name: "The Composer's Tomb", description: "Five movements. One name. The end of forgetting.", type: "BOSS", order: 5, levelRequirement: 20, bossKey: "forgotten-composer" },
    ],
  },
];

// Curated challenges attached to specific challenge/curse rooms (by area order).
export const curatedRoomChallenges: {
  areaKey: string;
  roomName: string;
  challenge: {
    type: string;
    title: string;
    description: string;
    difficulty: number;
    keySig?: string;
    meter?: string;
    lengthBars?: number;
    instrument?: string;
    requirement?: string;
    restriction?: string;
    xpReward: number;
    skillKey: string;
  };
}[] = [
  {
    areaKey: "hall-of-melody",
    roomName: "The Echoing Steps",
    challenge: {
      type: "CHALLENGE",
      title: "The Echoing Steps",
      description: "Write an eight-measure melody in C major with a single climax placed in measure six.",
      difficulty: 1,
      keySig: "C major",
      meter: "4/4",
      lengthBars: 8,
      instrument: "Any single-line instrument",
      requirement: "One clear climax, mostly stepwise motion",
      xpReward: 120,
      skillKey: "MELODY",
    },
  },
  {
    areaKey: "hall-of-melody",
    roomName: "Chamber of the Unrepeatable",
    challenge: {
      type: "CURSE",
      title: "Curse of the Unrepeatable",
      description: "Write sixteen measures in which the melody never repeats itself exactly. Variation is survival.",
      difficulty: 3,
      meter: "4/4",
      lengthBars: 16,
      restriction: "No measure may be an exact repeat of any earlier measure",
      requirement: "Keep one motif recognizable throughout",
      xpReward: 300,
      skillKey: "MELODY",
    },
  },
  {
    areaKey: "crypt-of-harmony",
    roomName: "The Resonant Ossuary",
    challenge: {
      type: "CHALLENGE",
      title: "The Resonant Ossuary",
      description: "Harmonize a simple melody using I, ii, IV, V and vi, ending with an authentic cadence.",
      difficulty: 2,
      keySig: "G major",
      meter: "4/4",
      lengthBars: 8,
      instrument: "Piano",
      requirement: "Use at least four different diatonic chords",
      xpReward: 180,
      skillKey: "HARMONY",
    },
  },
  {
    areaKey: "crypt-of-harmony",
    roomName: "Chamber of Silence",
    challenge: {
      type: "CURSE",
      title: "Curse of Silence",
      description: "Compose a piece that does not use the tonic chord until the final measure. Let the arrival be devastating.",
      difficulty: 4,
      lengthBars: 12,
      restriction: "No tonic chord until the final measure",
      requirement: "End with a convincing resolution to the withheld tonic",
      xpReward: 400,
      skillKey: "HARMONY",
    },
  },
  {
    areaKey: "tower-of-rhythm",
    roomName: "The Stair of Subdivisions",
    challenge: {
      type: "CHALLENGE",
      title: "The Stair of Subdivisions",
      description: "Write eight measures that progress from whole notes to sixteenth notes, one subdivision at a time.",
      difficulty: 2,
      meter: "4/4",
      lengthBars: 8,
      requirement: "Each two-measure group doubles the rhythmic speed",
      xpReward: 180,
      skillKey: "RHYTHM",
    },
  },
  {
    areaKey: "hall-of-the-virtuoso",
    roomName: "Gallery of Passagework",
    challenge: {
      type: "CHALLENGE",
      title: "Gallery of Passagework",
      description: "Write thirty-two measures featuring rapid passagework, shifting tonal centers, and at least three contrasting technical sections — all verified playable.",
      difficulty: 8,
      lengthBars: 32,
      instrument: "Solo instrument of your choice",
      requirement: "Three contrasting technical sections; every difficulty must serve a musical effect",
      restriction: "Nothing physically unrealistic — respect range, span, and breath",
      xpReward: 700,
      skillKey: "TECHNIQUE",
    },
  },
  {
    areaKey: "hall-of-the-virtuoso",
    roomName: "Chamber of the Left Hand",
    challenge: {
      type: "CURSE",
      title: "Curse of the Left Hand",
      description: "Compose a piano piece where the left hand is more melodically important than the right hand.",
      difficulty: 6,
      instrument: "Piano",
      lengthBars: 16,
      restriction: "The right hand may only accompany",
      requirement: "A complete melodic arc in the left hand",
      xpReward: 500,
      skillKey: "TECHNIQUE",
    },
  },
  {
    areaKey: "ancient-conservatory",
    roomName: "The Species Cells",
    challenge: {
      type: "CHALLENGE",
      title: "The Species Cells",
      description: "Write first-species counterpoint above the given cantus firmus, then a second-species version of the same line.",
      difficulty: 6,
      lengthBars: 10,
      requirement: "All first-species intervals consonant; passing tones only on weak beats in second species",
      xpReward: 450,
      skillKey: "COUNTERPOINT",
    },
  },
  {
    areaKey: "ancient-conservatory",
    roomName: "The Mirrored Cloister",
    challenge: {
      type: "CURSE",
      title: "Curse of the Mirror",
      description: "Compose a two-voice piece where the second voice is the strict inversion of the first, delayed by one measure.",
      difficulty: 7,
      lengthBars: 12,
      restriction: "Voice two must mirror voice one exactly",
      requirement: "The combination must remain consonant at phrase endings",
      xpReward: 550,
      skillKey: "COUNTERPOINT",
    },
  },
  {
    areaKey: "impressionist-gardens",
    roomName: "The Whole-Tone Pond",
    challenge: {
      type: "CHALLENGE",
      title: "The Whole-Tone Pond",
      description: "Compose twelve measures using the whole-tone scale, prioritizing color and atmosphere over resolution.",
      difficulty: 5,
      lengthBars: 12,
      requirement: "Whole-tone material throughout; texture changes at least once",
      xpReward: 400,
      skillKey: "EXPRESSION",
    },
  },
  {
    areaKey: "impressionist-gardens",
    roomName: "Garden of Endless Dusk",
    challenge: {
      type: "CURSE",
      title: "Curse of Endless Dusk",
      description: "Write a piece with no traditional cadence anywhere — endings must dissolve, not resolve.",
      difficulty: 5,
      lengthBars: 16,
      restriction: "No authentic, plagal, or half cadence",
      requirement: "The piece must still feel finished",
      xpReward: 420,
      skillKey: "EXPRESSION",
    },
  },
  {
    areaKey: "frozen-conservatory",
    roomName: "The Frostbitten Recital Hall",
    challenge: {
      type: "CHALLENGE",
      title: "The Frostbitten Recital Hall",
      description: "Compose in a minor key with extreme economy: sparse texture, wide silences, and echo-like repetitions that decay.",
      difficulty: 6,
      keySig: "B minor",
      lengthBars: 16,
      requirement: "At least a third of the piece is rests; every repetition quieter or thinner than its source",
      xpReward: 480,
      skillKey: "EXPRESSION",
    },
  },
  {
    areaKey: "frozen-conservatory",
    roomName: "The Frozen Choir Loft",
    challenge: {
      type: "CHALLENGE",
      title: "The Frozen Choir Loft",
      description: "Write for three voices that never sound simultaneously until the final chord.",
      difficulty: 7,
      lengthBars: 12,
      restriction: "Voices may overlap only in the final measure",
      requirement: "Each voice's line must be complete in itself",
      xpReward: 520,
      skillKey: "COUNTERPOINT",
    },
  },
  {
    areaKey: "inferno-of-virtuosity",
    roomName: "The First Circle: Passagework",
    challenge: {
      type: "CHALLENGE",
      title: "The First Circle: Passagework",
      description: "Compose sixteen measures of continuous sixteenth-note passagework that follows idiomatic scale and arpeggio patterns.",
      difficulty: 8,
      lengthBars: 16,
      instrument: "Piano or violin",
      requirement: "Patterns must lie under the hand; mark the musical purpose of each section",
      xpReward: 650,
      skillKey: "TECHNIQUE",
    },
  },
  {
    areaKey: "inferno-of-virtuosity",
    roomName: "The Second Circle: Endurance",
    challenge: {
      type: "CHALLENGE",
      title: "The Second Circle: Endurance",
      description: "Write a long-form technical study (32+ measures) that alternates peaks of strain with valleys of release.",
      difficulty: 9,
      lengthBars: 32,
      requirement: "At least three peak-valley cycles; the final peak is the highest",
      xpReward: 800,
      skillKey: "TECHNIQUE",
    },
  },
  {
    areaKey: "inferno-of-virtuosity",
    roomName: "The Third Circle: Coordination",
    challenge: {
      type: "CURSE",
      title: "Curse of the Split Mind",
      description: "Compose a piano piece where the two hands play in different meters simultaneously.",
      difficulty: 9,
      instrument: "Piano",
      lengthBars: 16,
      restriction: "Hands must remain in conflicting meters for at least twelve measures",
      requirement: "The composite rhythm must groove, not grind",
      xpReward: 850,
      skillKey: "RHYTHM",
    },
  },
  {
    areaKey: "cathedral-of-composition",
    roomName: "Ashes of the Choir",
    challenge: {
      type: "CHALLENGE",
      title: "Ashes of the Choir",
      description: "Write a choral texture using only open intervals — fourths, fifths, and octaves. Let the emptiness ring.",
      difficulty: 8,
      lengthBars: 16,
      instrument: "Choir (SATB)",
      restriction: "No thirds or sixths anywhere",
      requirement: "Four independent voices in open-interval harmony",
      xpReward: 700,
      skillKey: "HARMONY",
    },
  },
  {
    areaKey: "cathedral-of-composition",
    roomName: "The Collapsing Nave",
    challenge: {
      type: "CHALLENGE",
      title: "The Collapsing Nave",
      description: "Start with a stable diatonic theme and gradually destroy it through chromatic alteration until only its rhythm remains.",
      difficulty: 9,
      lengthBars: 24,
      requirement: "The destruction must be gradual and audible in stages",
      xpReward: 800,
      skillKey: "HARMONY",
    },
  },
  {
    areaKey: "cathedral-of-composition",
    roomName: "The Final Bell",
    challenge: {
      type: "CHALLENGE",
      title: "The Final Bell",
      description: "Create a final cadence that feels inevitable without using a traditional V–I progression.",
      difficulty: 9,
      lengthBars: 8,
      restriction: "No V–I motion at the close",
      requirement: "Inevitability by other means: voice leading, register, rhythm, or mode",
      xpReward: 750,
      skillKey: "FORM",
    },
  },
];

export const achievements = [
  { key: "first-lesson", name: "First Light", description: "Complete your first Academy lesson.", icon: "📖", xpReward: 50, criteria: "LESSONS_COMPLETED", threshold: 1 },
  { key: "first-composition", name: "The First Page", description: "Submit your first composition.", icon: "🖋️", xpReward: 75, criteria: "COMPOSITIONS", threshold: 1 },
  { key: "first-challenge", name: "Dungeon Delver", description: "Complete your first Dungeon challenge.", icon: "⚔️", xpReward: 75, criteria: "CHALLENGES_COMPLETED", threshold: 1 },
  { key: "first-boss", name: "Giantsbane", description: "Defeat your first boss.", icon: "💀", xpReward: 200, criteria: "BOSSES_DEFEATED", threshold: 1 },
  { key: "streak-7", name: "Week of Fire", description: "Keep the Creative Flame alive for 7 days.", icon: "🔥", xpReward: 150, criteria: "STREAK", threshold: 7 },
  { key: "streak-30", name: "Month of Fire", description: "Keep the Creative Flame alive for 30 days.", icon: "🌋", xpReward: 500, criteria: "STREAK", threshold: 30 },
  { key: "streak-100", name: "Legendary Composer", description: "Keep the Creative Flame alive for 100 days.", icon: "☄️", xpReward: 2000, criteria: "STREAK", threshold: 100 },
  { key: "scholar", name: "Scholar of the Academy", description: "Complete 10 Academy lessons.", icon: "🎓", xpReward: 300, criteria: "LESSONS_COMPLETED", threshold: 10 },
  { key: "curse-breaker", name: "Curse Breaker", description: "Complete 3 Curse Room challenges.", icon: "🕯️", xpReward: 250, criteria: "CURSES_COMPLETED", threshold: 3 },
  { key: "puzzle-master", name: "Riddle of the Keys", description: "Solve 5 Puzzle Rooms.", icon: "🧩", xpReward: 250, criteria: "PUZZLES_COMPLETED", threshold: 5 },
  { key: "level-10", name: "Journeyman Composer", description: "Reach Composer Level 10.", icon: "🏅", xpReward: 300, criteria: "LEVEL", threshold: 10 },
  { key: "level-25", name: "Master of the Halls", description: "Reach Composer Level 25.", icon: "👑", xpReward: 800, criteria: "LEVEL", threshold: 25 },
  { key: "skill-10", name: "Specialist", description: "Raise any single skill to level 10.", icon: "⭐", xpReward: 300, criteria: "SKILL_LEVEL", threshold: 10 },
  { key: "specialized", name: "A Name Among Names", description: "Unlock your first Composer Specialization.", icon: "🎭", xpReward: 400, criteria: "SPECIALIZATIONS", threshold: 1 },
  { key: "daily-5", name: "Dawn Patrol", description: "Complete 5 Daily Dungeon Challenges.", icon: "🌅", xpReward: 250, criteria: "DAILIES_COMPLETED", threshold: 5 },
];

export const specializations = [
  {
    key: "VIRTUOSO",
    name: "The Virtuoso",
    description: "Difficulty as drama. Speed, complex rhythm, and repertoire that pushes performers to their edge.",
    focus: ["Technical difficulty", "Speed", "Complex rhythms", "Demanding repertoire"],
    icon: "🎻",
    levelRequirement: 12,
    skillKey: "TECHNIQUE",
    requiredSkillLevel: 8,
  },
  {
    key: "IMPRESSIONIST",
    name: "The Impressionist",
    description: "Color over cadence. Atmosphere, harmonic ambiguity, and modal light on water.",
    focus: ["Color", "Atmosphere", "Harmonic ambiguity", "Texture", "Modal sounds"],
    icon: "🌫️",
    levelRequirement: 12,
    skillKey: "EXPRESSION",
    requiredSkillLevel: 8,
  },
  {
    key: "CLASSICIST",
    name: "The Classicist",
    description: "Architecture in sound. Form, counterpoint, and themes developed with inevitable logic.",
    focus: ["Form", "Structure", "Counterpoint", "Thematic development"],
    icon: "🏛️",
    levelRequirement: 12,
    skillKey: "FORM",
    requiredSkillLevel: 8,
  },
  {
    key: "CINEMATIC",
    name: "The Cinematic",
    description: "Music that tells stories. Emotion, drama, and orchestration in widescreen.",
    focus: ["Emotion", "Storytelling", "Drama", "Orchestration"],
    icon: "🎬",
    levelRequirement: 12,
    skillKey: "ORCHESTRATION",
    requiredSkillLevel: 6,
  },
  {
    key: "EXPERIMENTALIST",
    name: "The Experimentalist",
    description: "Rules are raw material. Unusual techniques, new sounds, structures no one has named yet.",
    focus: ["Unusual techniques", "Unusual rules", "New sounds", "Unconventional structures"],
    icon: "⚗️",
    levelRequirement: 12,
    skillKey: "EXPRESSION",
    requiredSkillLevel: 6,
  },
];

// Challenge generator components. Difficulty ranges keep combinations sane.
export const challengeComponents = [
  // KEYS
  { type: "KEY", value: "C major", minDifficulty: 1, maxDifficulty: 4, weight: 3 },
  { type: "KEY", value: "G major", minDifficulty: 1, maxDifficulty: 5, weight: 3 },
  { type: "KEY", value: "F major", minDifficulty: 1, maxDifficulty: 5, weight: 2 },
  { type: "KEY", value: "A minor", minDifficulty: 1, maxDifficulty: 5, weight: 3 },
  { type: "KEY", value: "D major", minDifficulty: 2, maxDifficulty: 6, weight: 2 },
  { type: "KEY", value: "E minor", minDifficulty: 2, maxDifficulty: 6, weight: 2 },
  { type: "KEY", value: "B-flat major", minDifficulty: 3, maxDifficulty: 7, weight: 2 },
  { type: "KEY", value: "D minor", minDifficulty: 3, maxDifficulty: 7, weight: 2 },
  { type: "KEY", value: "E-flat major", minDifficulty: 4, maxDifficulty: 8, weight: 2 },
  { type: "KEY", value: "F-sharp minor", minDifficulty: 5, maxDifficulty: 10, weight: 2 },
  { type: "KEY", value: "C-sharp major", minDifficulty: 7, maxDifficulty: 10, weight: 1 },
  { type: "KEY", value: "B minor", minDifficulty: 4, maxDifficulty: 9, weight: 2 },
  // METERS
  { type: "METER", value: "4/4", minDifficulty: 1, maxDifficulty: 10, weight: 4 },
  { type: "METER", value: "3/4", minDifficulty: 1, maxDifficulty: 10, weight: 3 },
  { type: "METER", value: "6/8", minDifficulty: 2, maxDifficulty: 10, weight: 3, skillKey: "RHYTHM" },
  { type: "METER", value: "2/4", minDifficulty: 1, maxDifficulty: 8, weight: 2 },
  { type: "METER", value: "5/8", minDifficulty: 5, maxDifficulty: 10, weight: 2, skillKey: "RHYTHM" },
  { type: "METER", value: "7/8", minDifficulty: 6, maxDifficulty: 10, weight: 2, skillKey: "RHYTHM" },
  { type: "METER", value: "9/8", minDifficulty: 5, maxDifficulty: 10, weight: 1, skillKey: "RHYTHM" },
  // LENGTHS (bars)
  { type: "LENGTH", value: "8", minDifficulty: 1, maxDifficulty: 4, weight: 3 },
  { type: "LENGTH", value: "12", minDifficulty: 2, maxDifficulty: 6, weight: 2 },
  { type: "LENGTH", value: "16", minDifficulty: 3, maxDifficulty: 8, weight: 3 },
  { type: "LENGTH", value: "24", minDifficulty: 5, maxDifficulty: 10, weight: 2 },
  { type: "LENGTH", value: "32", minDifficulty: 7, maxDifficulty: 10, weight: 2 },
  // INSTRUMENTS
  { type: "INSTRUMENT", value: "Piano", minDifficulty: 1, maxDifficulty: 10, weight: 4 },
  { type: "INSTRUMENT", value: "Solo violin", minDifficulty: 3, maxDifficulty: 10, weight: 2, skillKey: "TECHNIQUE" },
  { type: "INSTRUMENT", value: "Solo cello", minDifficulty: 3, maxDifficulty: 10, weight: 2 },
  { type: "INSTRUMENT", value: "Flute", minDifficulty: 2, maxDifficulty: 9, weight: 2 },
  { type: "INSTRUMENT", value: "String quartet", minDifficulty: 5, maxDifficulty: 10, weight: 2, skillKey: "COUNTERPOINT" },
  { type: "INSTRUMENT", value: "Voice and piano", minDifficulty: 2, maxDifficulty: 8, weight: 2, skillKey: "MELODY" },
  { type: "INSTRUMENT", value: "Small orchestra", minDifficulty: 7, maxDifficulty: 10, weight: 1, skillKey: "ORCHESTRATION" },
  // STYLES
  { type: "STYLE", value: "Classical clarity", minDifficulty: 1, maxDifficulty: 10, weight: 2 },
  { type: "STYLE", value: "Impressionist haze", minDifficulty: 4, maxDifficulty: 10, weight: 2, skillKey: "EXPRESSION" },
  { type: "STYLE", value: "Cinematic sweep", minDifficulty: 3, maxDifficulty: 10, weight: 2, skillKey: "ORCHESTRATION" },
  { type: "STYLE", value: "Dance-like", minDifficulty: 2, maxDifficulty: 9, weight: 2, skillKey: "RHYTHM" },
  { type: "STYLE", value: "Nocturne stillness", minDifficulty: 3, maxDifficulty: 9, weight: 2, skillKey: "EXPRESSION" },
  { type: "STYLE", value: "Baroque drive", minDifficulty: 5, maxDifficulty: 10, weight: 1, skillKey: "COUNTERPOINT" },
  // REQUIREMENTS
  { type: "REQUIREMENT", value: "Develop one motif at least three times", minDifficulty: 3, maxDifficulty: 10, weight: 3, skillKey: "FORM" },
  { type: "REQUIREMENT", value: "Include a question-and-answer phrase pair", minDifficulty: 1, maxDifficulty: 6, weight: 3, skillKey: "MELODY" },
  { type: "REQUIREMENT", value: "Use at least four different chords", minDifficulty: 2, maxDifficulty: 6, weight: 3, skillKey: "HARMONY" },
  { type: "REQUIREMENT", value: "Modulate to a related key and return", minDifficulty: 5, maxDifficulty: 10, weight: 2, skillKey: "HARMONY" },
  { type: "REQUIREMENT", value: "Include one deceptive cadence", minDifficulty: 4, maxDifficulty: 9, weight: 2, skillKey: "HARMONY" },
  { type: "REQUIREMENT", value: "Write a countermelody against the main line", minDifficulty: 5, maxDifficulty: 10, weight: 2, skillKey: "COUNTERPOINT" },
  { type: "REQUIREMENT", value: "Place the climax in the final third of the piece", minDifficulty: 2, maxDifficulty: 8, weight: 3, skillKey: "MELODY" },
  { type: "REQUIREMENT", value: "Use syncopation as a central feature", minDifficulty: 3, maxDifficulty: 9, weight: 2, skillKey: "RHYTHM" },
  { type: "REQUIREMENT", value: "Feature rapid passagework in at least one section", minDifficulty: 7, maxDifficulty: 10, weight: 2, skillKey: "TECHNIQUE" },
  { type: "REQUIREMENT", value: "Change texture at least twice", minDifficulty: 4, maxDifficulty: 10, weight: 2, skillKey: "EXPRESSION" },
  // RESTRICTIONS
  { type: "RESTRICTION", value: "No perfect authentic cadence anywhere", minDifficulty: 5, maxDifficulty: 10, weight: 2, skillKey: "HARMONY" },
  { type: "RESTRICTION", value: "Only three distinct pitches allowed", minDifficulty: 4, maxDifficulty: 9, weight: 1, skillKey: "MELODY" },
  { type: "RESTRICTION", value: "No rhythm may repeat in consecutive measures", minDifficulty: 5, maxDifficulty: 10, weight: 2, skillKey: "RHYTHM" },
  { type: "RESTRICTION", value: "The melody may never repeat exactly", minDifficulty: 4, maxDifficulty: 10, weight: 2, skillKey: "MELODY" },
  { type: "RESTRICTION", value: "You must change meter at least once", minDifficulty: 5, maxDifficulty: 10, weight: 2, skillKey: "RHYTHM" },
  { type: "RESTRICTION", value: "The interval of a third is forbidden in the melody", minDifficulty: 6, maxDifficulty: 10, weight: 1, skillKey: "MELODY" },
  { type: "RESTRICTION", value: "Begin and end in different registers", minDifficulty: 3, maxDifficulty: 8, weight: 2, skillKey: "EXPRESSION" },
  // TITLE FRAGMENTS
  { type: "TITLE_FRAGMENT", value: "the Sunken Bell", minDifficulty: 1, maxDifficulty: 10, weight: 1 },
  { type: "TITLE_FRAGMENT", value: "the Marble Stair", minDifficulty: 1, maxDifficulty: 10, weight: 1 },
  { type: "TITLE_FRAGMENT", value: "the Whispering Vault", minDifficulty: 1, maxDifficulty: 10, weight: 1 },
  { type: "TITLE_FRAGMENT", value: "the Seven Candles", minDifficulty: 1, maxDifficulty: 10, weight: 1 },
  { type: "TITLE_FRAGMENT", value: "the Broken Clavier", minDifficulty: 1, maxDifficulty: 10, weight: 1 },
  { type: "TITLE_FRAGMENT", value: "the Midnight Choir", minDifficulty: 1, maxDifficulty: 10, weight: 1 },
  { type: "TITLE_FRAGMENT", value: "the Serpent's Scale", minDifficulty: 1, maxDifficulty: 10, weight: 1 },
  { type: "TITLE_FRAGMENT", value: "the Ivory Gate", minDifficulty: 1, maxDifficulty: 10, weight: 1 },
  { type: "TITLE_FRAGMENT", value: "the Forgotten Page", minDifficulty: 1, maxDifficulty: 10, weight: 1 },
  { type: "TITLE_FRAGMENT", value: "the Last Fermata", minDifficulty: 1, maxDifficulty: 10, weight: 1 },
];

// Placement Trial question bank (not tied to any lesson quiz).
export const placementQuestions = [
  { subject: "NOTES", difficulty: 1, prompt: "Which letter comes after G in the musical alphabet?", choices: ["H", "A", "B", "C"], answerIndex: 1, explanation: "The musical alphabet cycles A–G." },
  { subject: "ACCIDENTALS", difficulty: 1, prompt: "A flat (♭) does what to a note?", choices: ["Raises it a half step", "Lowers it a half step", "Doubles it", "Silences it"], answerIndex: 1, explanation: "Flats lower pitch by a half step." },
  { subject: "RHYTHM", difficulty: 1, prompt: "How many eighth notes equal one half note?", choices: ["2", "3", "4", "8"], answerIndex: 2, explanation: "A half note = 2 beats = 4 eighth notes." },
  { subject: "METER", difficulty: 2, prompt: "In 4/4 time, the bottom number means:", choices: ["Four measures", "The quarter note gets the beat", "Four instruments", "Play four times"], answerIndex: 1, explanation: "The lower numeral names the beat unit." },
  { subject: "SCALES", difficulty: 2, prompt: "The major scale pattern is:", choices: ["W-W-H-W-W-W-H", "W-H-W-W-H-W-W", "H-H-W-W-W-H-W", "W-W-W-H-W-W-H"], answerIndex: 0, explanation: "Whole-Whole-Half-Whole-Whole-Whole-Half." },
  { subject: "SCALES", difficulty: 3, prompt: "The relative minor of G major is:", choices: ["D minor", "B minor", "E minor", "G minor"], answerIndex: 2, explanation: "The relative minor starts on the 6th degree: E." },
  { subject: "INTERVALS", difficulty: 3, prompt: "C up to A is what interval?", choices: ["5th", "6th", "7th", "4th"], answerIndex: 1, explanation: "C-D-E-F-G-A: six letter names, a sixth." },
  { subject: "CHORDS", difficulty: 3, prompt: "A minor triad consists of:", choices: ["Root, major 3rd, 5th", "Root, minor 3rd, 5th", "Root, 4th, 5th", "Root, 2nd, 5th"], answerIndex: 1, explanation: "Minor third + perfect fifth above the root." },
  { subject: "FUNCTIONS", difficulty: 4, prompt: "In a major key, which chord is the dominant?", choices: ["I", "IV", "V", "vi"], answerIndex: 2, explanation: "The chord on scale degree 5." },
  { subject: "INVERSIONS", difficulty: 4, prompt: "C/G means a C major chord with:", choices: ["G omitted", "G in the bass", "G doubled", "G sharp"], answerIndex: 1, explanation: "Slash notation names the bass note: second inversion here." },
  { subject: "CADENCES", difficulty: 4, prompt: "A half cadence ends on:", choices: ["I", "IV", "V", "vi"], answerIndex: 2, explanation: "Half cadences pause on the dominant." },
  { subject: "CIRCLE_OF_FIFTHS", difficulty: 4, prompt: "How many sharps are in D major?", choices: ["1", "2", "3", "4"], answerIndex: 1, explanation: "D major has F♯ and C♯." },
  { subject: "MODULATION", difficulty: 5, prompt: "The smoothest modulations usually travel to keys that:", choices: ["Share many notes with the home key", "Share no notes", "Are a tritone away", "Have more flats"], answerIndex: 0, explanation: "Closely related keys share six of seven notes." },
  { subject: "SECONDARY_DOMINANTS", difficulty: 5, prompt: "V/vi in C major is:", choices: ["A7", "E7", "D7", "B7"], answerIndex: 1, explanation: "The dominant of A minor (vi) is E7." },
  { subject: "COUNTERPOINT", difficulty: 6, prompt: "Which parallel motion is forbidden in strict counterpoint?", choices: ["Parallel 3rds", "Parallel 6ths", "Parallel 5ths", "Parallel 10ths"], answerIndex: 2, explanation: "Parallel perfect 5ths and octaves destroy voice independence." },
  { subject: "AUGMENTATION", difficulty: 6, prompt: "Diminution of a theme means:", choices: ["Playing it quieter", "Halving its note values", "Lowering its pitch", "Removing notes"], answerIndex: 1, explanation: "Diminution compresses durations; augmentation stretches them." },
  { subject: "FORM", difficulty: 6, prompt: "Sonata form's three main sections are:", choices: ["Verse, chorus, bridge", "Exposition, development, recapitulation", "A, B, A", "Intro, solo, outro"], answerIndex: 1, explanation: "Exposition–development–recapitulation." },
  { subject: "COUNTERPOINT", difficulty: 7, prompt: "In a fugue, stretto is used to:", choices: ["Slow the tempo", "Overlap subject entries for intensity", "End the piece quietly", "Change key"], answerIndex: 1, explanation: "Overlapping entries compress and intensify." },
  { subject: "FORM", difficulty: 7, prompt: "Writing a physically impossible passage is best called:", choices: ["Idiomatic virtuosity", "Effective difficulty", "Unrealistic writing", "Advanced technique"], answerIndex: 2, explanation: "If it cannot be executed, it is not virtuosity — it is a mistake." },
  { subject: "MODULATION", difficulty: 7, prompt: "An enharmonic modulation reinterprets:", choices: ["The tempo", "A chord's spelling to pivot into a distant key", "The meter", "The instrumentation"], answerIndex: 1, explanation: "E.g., a German 6th respelled as a dominant 7th opens a distant door." },
];
